import { defaultClosingTasks } from "@/repositories/local-storage-erp.repository";
import type { ChartOfAccount, ErpData, JournalEntry, JournalLine } from "@/types/erp";
import { uid } from "@/utils/format";

const temporaryTypes = new Set(["revenue", "cost", "expense"]);
const permanentTypes = new Set(["asset", "liability", "equity"]);

function balancesAt(data: ErpData, companyId: string, to: string, from?: string) {
  const balances = new Map<string, number>();
  data.journalEntries
    .filter((entry) => entry.companyId === companyId && entry.status === "posted" && entry.date <= to && (!from || entry.date >= from))
    .flatMap((entry) => entry.lines)
    .forEach((line) => balances.set(line.accountCode, (balances.get(line.accountCode) ?? 0) + line.debit - line.credit));
  return balances;
}

function accountLine(account: ChartOfAccount, balance: number, reverse: boolean, description: string): JournalLine {
  const value = reverse ? -balance : balance;
  return { accountCode: account.code, accountName: account.name, description, debit: Math.max(value, 0), credit: Math.max(-value, 0), sourceModule: "Period Closing" };
}

function journal(data: ErpData, input: { companyId: string; date: string; description: string; type: "closing" | "opening"; lines: JournalLine[] }): JournalEntry {
  const difference = input.lines.reduce((sum, line) => sum + line.debit - line.credit, 0);
  if (!input.lines.length || Math.abs(difference) > .005) throw new Error("تعذر إنشاء قيد الإقفال: القيد غير متوازن أو بلا سطور.");
  const timestamp = new Date().toISOString();
  const year = Number(input.date.slice(0, 4));
  const sequence = data.journalEntries.filter((entry) => entry.companyId === input.companyId && entry.date.startsWith(String(year))).length + 1;
  const number = `${input.type === "closing" ? "CL" : "OP"}-${year}-${String(sequence).padStart(4, "0")}`;
  return { id: uid(input.type), createdAt: timestamp, updatedAt: timestamp, number, companyId: input.companyId, date: input.date, description: input.description, reference: number, journalType: input.type, sourceModule: "Period Closing", sourceType: input.type === "closing" ? "Year-End Closing" : "New Fiscal Year Opening", sourceNumber: number, automatic: true, lines: input.lines.map((line) => ({ ...line, reference: number, sourceDocument: number })), status: "posted", createdBy: "System", postedBy: "Finance Manager", auditTrail: [{ action: "create", user: "System", timestamp, note: "Generated by controlled year-end workflow" }, { action: "review", user: "Finance Reviewer", timestamp }, { action: "post", user: "Finance Manager", timestamp }] };
}

function retainedEarningsAccount(data: ErpData, companyId: string) {
  return data.chartOfAccounts.find((account) => account.companyId === companyId && account.type === "equity" && !account.isControl && /أرباح محتجزة|retained earnings/i.test(`${account.name} ${account.nameEn}`))
    ?? data.chartOfAccounts.find((account) => account.companyId === companyId && account.type === "equity" && !account.isControl);
}

export function createYearEndClosingJournal(data: ErpData, companyId: string, fiscalYear: number): JournalEntry | undefined {
  const date = `${fiscalYear}-12-31`;
  if (data.journalEntries.some((entry) => entry.companyId === companyId && entry.journalType === "closing" && entry.sourceType === "Year-End Closing" && entry.date === date)) throw new Error("تم تنفيذ إقفال هذه السنة بالفعل.");
  const accounts = data.chartOfAccounts.filter((account) => account.companyId === companyId && account.active);
  const balances = balancesAt(data, companyId, date, `${fiscalYear}-01-01`);
  const lines = accounts.filter((account) => temporaryTypes.has(account.type) && Math.abs(balances.get(account.code) ?? 0) > .005).map((account) => accountLine(account, balances.get(account.code) ?? 0, true, "إقفال رصيد السنة"));
  if (!lines.length) return undefined;
  const difference = lines.reduce((sum, line) => sum + line.debit - line.credit, 0);
  const retained = retainedEarningsAccount(data, companyId);
  if (!retained) throw new Error("يجب إعداد حساب أرباح محتجزة تفصيلي قبل إقفال السنة.");
  lines.push(accountLine(retained, difference, true, "تحويل صافي نتيجة السنة إلى الأرباح المحتجزة"));
  return journal(data, { companyId, date, description: `إقفال السنة المالية ${fiscalYear}`, type: "closing", lines });
}

export function createCarryForwardJournal(data: ErpData, companyId: string, fiscalYear: number): JournalEntry | undefined {
  const openingDate = `${fiscalYear + 1}-01-01`;
  if (data.journalEntries.some((entry) => entry.companyId === companyId && entry.journalType === "opening" && entry.sourceType === "New Fiscal Year Opening" && entry.date === openingDate)) throw new Error("تم ترحيل الأرصدة إلى هذه السنة بالفعل.");
  const accounts = data.chartOfAccounts.filter((account) => account.companyId === companyId && account.active && permanentTypes.has(account.type));
  const balances = balancesAt(data, companyId, `${fiscalYear}-12-31`);
  const lines = accounts.filter((account) => Math.abs(balances.get(account.code) ?? 0) > .005).map((account) => accountLine(account, balances.get(account.code) ?? 0, false, "رصيد مرحل من السنة السابقة"));
  if (!lines.length) return undefined;
  return journal(data, { companyId, date: openingDate, description: `أرصدة افتتاحية مرحّلة من ${fiscalYear}`, type: "opening", lines });
}

export function closeFiscalYear(data: ErpData, companyId: string, fiscalYear: number): ErpData {
  const closing = createYearEndClosingJournal(data, companyId, fiscalYear);
  const withClosing = closing ? { ...data, journalEntries: [...data.journalEntries, closing] } : data;
  const opening = createCarryForwardJournal(withClosing, companyId, fiscalYear);
  const timestamp = new Date().toISOString();
  const existingMonths = new Set(data.fiscalPeriods.filter((period) => period.companyId === companyId && period.fiscalYear === fiscalYear + 1).map((period) => period.month));
  const newPeriods = Array.from({ length: 12 }, (_, index) => index + 1).filter((month) => !existingMonths.has(month)).map((month) => ({ id: uid("period"), companyId, fiscalYear: fiscalYear + 1, month, name: new Date(fiscalYear + 1, month - 1, 1).toLocaleDateString("ar-EG", { month: "long", year: "numeric" }), status: "open" as const, closingTasks: defaultClosingTasks(), createdAt: timestamp, updatedAt: timestamp }));
  return { ...withClosing, journalEntries: opening ? [...withClosing.journalEntries, opening] : withClosing.journalEntries, fiscalPeriods: [...data.fiscalPeriods.map((period) => period.companyId === companyId && period.fiscalYear === fiscalYear ? { ...period, status: "closed" as const, updatedAt: timestamp } : period), ...newPeriods] };
}
