"use client";

import { useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { AlertTriangle, BookOpen, CheckCircle2, ClipboardCheck, FileBarChart, Landmark, RotateCcw, Scale, ShieldAlert, WalletCards } from "lucide-react";
import { DataTable } from "@/components/shared/data-table";
import { Modal } from "@/components/shared/modal";
import { AccountingOperations } from "@/components/accounting/accounting-operations";
import { inferAccountClassification, validSections, withAccountClassification } from "@/services/account-classification";
import { calculateTrialBalance, companyIncomeStatement, projectCostLedger, projectFinancialPosition, projectIncomeStatement, projectJournalEntries, projectLedger, projectReconciliation, projectTrialBalance, reverseJournal } from "@/services/business-calculations";
import { closeFiscalYear } from "@/services/period-closing";
import { buildGeneralLedger } from "@/services/general-ledger";
import { useUiStore } from "@/store/ui-store";
import type { AccountingMapping, AccountType, ChartOfAccount, ErpData, JournalEntry, Project } from "@/types/erp";
import { formatMoney, uid } from "@/utils/format";

type Commit = (data: ErpData, message?: string) => void;
type AccountingView = "core" | "control" | "ledger" | "trial" | "income" | "accounts" | "mapping" | "closing";
export type AccountingRoute = AccountingView | "documents" | "journals" | "open-items" | "exceptions";
type ProjectView = "workspace" | "snapshot" | "ledger" | "trial" | "cost" | "income" | "position" | "journals";

export function AccountingCenter({ data, commit, companyId: contextCompanyId, route }: { data: ErpData; commit: Commit; companyId?: string; route?: AccountingRoute }) {
  const initialAccountingView: AccountingView = route === "documents" || route === "journals" || route === "open-items" || route === "exceptions" ? "core" : route ?? "core";
  const [view, setView] = useState<AccountingView>(initialAccountingView);
  const [selectedJournal, setSelectedJournal] = useState<JournalEntry>();
  const [projectFilter, setProjectFilter] = useState("all");
  const openChartOfAccounts = useUiStore((state) => state.setModule);
  const companyId = contextCompanyId ?? data.companies.find((company) => company.status === "active")?.id ?? data.companies[0]?.id;
  const companyAccounts = data.chartOfAccounts.filter((account) => !companyId || account.companyId === companyId);
  const entries = data.journalEntries.filter((entry) => (!companyId || entry.companyId === companyId) && (projectFilter === "all" || entry.projectId === projectFilter || entry.lines.some((line) => line.projectId === projectFilter)));
  const trial = calculateTrialBalance(entries);
  const income = companyId ? companyIncomeStatement(data, companyId) : { revenue: 0, directCosts: 0, grossProfit: 0, expenses: 0, operatingProfit: 0 };
  const totalDebit = entries.filter((entry) => entry.status === "posted").flatMap((entry) => entry.lines).reduce((sum, line) => sum + line.debit, 0);
  const totalCredit = entries.filter((entry) => entry.status === "posted").flatMap((entry) => entry.lines).reduce((sum, line) => sum + line.credit, 0);
  const companyProjects = data.projects.filter((project) => !companyId || project.companyId === companyId);
  const unpostedSources = findUnpostedSources(data, companyId);
  const reconciliationIssues = companyProjects.map((project) => ({ project, ...projectReconciliation(project.id, data) })).filter((row) => Math.abs(row.difference) > 0.01);
  const companyPeriods = data.fiscalPeriods.filter((period) => !companyId || period.companyId === companyId);
  const currentPeriod = companyPeriods.find((period) => period.status === "open") ?? companyPeriods[0];
  const completedTasks = currentPeriod?.closingTasks?.filter((task) => task.completed).length ?? 0;
  if (companyAccounts.length === 0 && route !== "accounts" && view !== "accounts") return <AccountingEmpty title="لم يتم إعداد دليل الحسابات بعد" action="+ إعداد دليل الحسابات" onAction={() => openChartOfAccounts("chart-accounts")}/>;
  if (route === "journals" && entries.length === 0) return <AccountingEmpty title="لا توجد قيود يومية حتى الآن"/>;
  if (route === "ledger" && !entries.some((entry) => entry.status === "posted" && entry.lines.length > 0)) return <AccountingEmpty title="لا توجد حركات في الفترة المحددة"/>;
  return <>
    {!route && <div className="accounting-toolbar">
      <div className="segment-tabs">{([{ key: "core", label: "مركز الحسابات", icon: WalletCards }, { key: "control", label: "الرقابة المالية", icon: ShieldAlert }, { key: "ledger", label: "الأستاذ العام", icon: BookOpen }, { key: "trial", label: "ميزان المراجعة", icon: Scale }, { key: "income", label: "قائمة الدخل", icon: FileBarChart }, { key: "accounts", label: "دليل الحسابات", icon: Landmark }, { key: "mapping", label: "ربط الحسابات", icon: WalletCards }, { key: "closing", label: "الإقفال الشهري", icon: ClipboardCheck }] as const).map((item) => <button key={item.key} className={view === item.key ? "active" : ""} onClick={() => setView(item.key)}><item.icon size={15}/>{item.label}</button>)}</div>
      <select aria-label="نطاق المشروع" className="select" value={projectFilter} onChange={(event) => setProjectFilter(event.target.value)}><option value="all">كل المشروعات — حسابات الشركة</option>{companyProjects.map((project) => <option key={project.id} value={project.id}>{project.code} — {project.name}</option>)}</select>
    </div>}
    {view === "core" && companyId && <AccountingOperations data={data} companyId={companyId} projectId={projectFilter === "all" ? undefined : projectFilter} commit={commit} onJournal={setSelectedJournal} initialView={route === "documents" ? "documents" : route === "journals" ? "journals" : route === "open-items" ? "open-items" : route === "exceptions" ? "exceptions" : "workspace"} hideNavigation={Boolean(route)}/>}
    {view === "control" && <><div className="metrics"><AccountingMetric label="الفترة الحالية" value={currentPeriod?.name ?? "—"} note={currentPeriod?.status ?? "—"} icon={ClipboardCheck}/><AccountingMetric label="إجمالي المدين" value={formatMoney(totalDebit, data.settings.currency)} note="قيود مرحلة" icon={Landmark}/><AccountingMetric label="إجمالي الدائن" value={formatMoney(totalCredit, data.settings.currency)} note={Math.abs(totalDebit-totalCredit)<.01?"الميزان متوازن":"فرق يحتاج مراجعة"} icon={Scale} good={Math.abs(totalDebit-totalCredit)<.01}/><AccountingMetric label="الإقفال الشهري" value={`${completedTasks} / ${currentPeriod?.closingTasks.length ?? 0}`} note="مهام مكتملة" icon={ClipboardCheck}/></div><div className="control-grid"><ControlPanel title="استثناءات الدورة المحاسبية" icon={ShieldAlert} items={[{ label: "قيود مسودة غير متوازنة", value: String(entries.filter((entry) => entry.status === "draft" && !isBalanced(entry)).length), danger: true }, { label: "مستندات تشغيل غير مرحلة", value: String(unpostedSources.length), danger: unpostedSources.length > 0 }, { label: "فروق تسوية تكلفة المشروعات", value: String(reconciliationIssues.length), danger: reconciliationIssues.length > 0 }, { label: "مشروعات بدون مركز تكلفة", value: String(companyProjects.filter((project) => !project.costCenterCode).length), danger: true }]}/><ControlPanel title="تغطية الربط المحاسبي" icon={CheckCircle2} items={[{ label: "ربط الشركة الحالية", value: data.accountingMappings.some((mapping) => mapping.companyId === companyId)?"مكتمل":"غير مكتمل" }, { label: "القيود الآلية", value: String(entries.filter((entry) => entry.automatic).length) }, { label: "القيود اليدوية", value: String(entries.filter((entry) => !entry.automatic).length) }, { label: "الحسابات النشطة", value: String(companyAccounts.filter((account) => account.active).length) }]}/></div>{unpostedSources.length>0&&<div className="card" style={{marginTop:16}}><div className="card-head"><div><h3>مستندات لم تُرحّل</h3><p>عمليات تشغيلية لم يظهر أثرها المحاسبي بعد</p></div><span className="badge draft">{unpostedSources.length}</span></div><div className="card-body exception-list">{unpostedSources.map((item)=><div key={item.reference}><div><strong>{item.reference}</strong><small>{item.module} · {item.description}</small></div><span className="badge draft">معلّق</span></div>)}</div></div>}</>}
    {view === "ledger" && <GeneralLedger entries={entries} currency={data.settings.currency} projects={data.projects} onJournal={setSelectedJournal}/>} 
    {view === "trial" && <TrialBalance rows={trial} currency={data.settings.currency}/>} 
    {view === "income" && <IncomeStatement data={income} currency={data.settings.currency}/>} 
    {view === "accounts" && companyId && <ChartOfAccounts data={data} companyId={companyId} commit={commit}/>}
    {view === "mapping" && companyId && <MappingEditor data={data} companyId={companyId} commit={commit}/>} 
    {view === "closing" && currentPeriod && <><ClosingChecklist data={data} periodId={currentPeriod.id} commit={commit}/>{companyId&&<YearEndClosing data={data} companyId={companyId} fiscalYear={Math.max(...companyPeriods.map((period)=>period.fiscalYear))} commit={commit}/>}</>}
    <JournalDetails journal={selectedJournal} data={data} onClose={()=>setSelectedJournal(undefined)} onReverse={(journal)=>{const reversal=reverseJournal(journal,data);commit({...data,journalEntries:[...data.journalEntries.map((entry)=>entry.id===journal.id?{...entry,status:"reversed" as const,updatedAt:new Date().toISOString(),auditTrail:[...entry.auditTrail,{action:"reverse" as const,user:"Finance Manager",timestamp:new Date().toISOString()}]}:entry),reversal]},`تم إنشاء القيد العكسي ${reversal.number}`);setSelectedJournal(reversal);}}/>
  </>;
}

export function ProjectAccountingCenter({ data, projects, commit }: { data: ErpData; projects: Project[]; commit?: Commit }) {
  const [projectId, setProjectId] = useState(projects[0]?.id ?? data.projects[0]?.id ?? "");
  const [view, setView] = useState<ProjectView>("workspace");
  const [selectedJournal, setSelectedJournal] = useState<JournalEntry>();
  const project = data.projects.find((item) => item.id === projectId) ?? projects[0] ?? data.projects[0];
  if (!project) return <div className="empty"><strong>لا توجد مشروعات</strong></div>;
  const income = projectIncomeStatement(project.id, data);
  const position = projectFinancialPosition(project.id, data);
  const reconciliation = projectReconciliation(project.id, data);
  const committedCost = position.commitments;
  const forecastCost = project.progress ? reconciliation.accountingCost / (project.progress / 100) : project.budget;
  const forecastProfit = project.contractValue - forecastCost;
  return <>
    <div className="project-accounting-head"><div><span>البعد المحاسبي للمشروع</span><h3>{project.code} — {project.name}</h3><p>{project.costCenterCode} · {project.wbsCode}</p></div><select className="select" value={project.id} onChange={(event)=>setProjectId(event.target.value)}>{projects.map((item)=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></div>
    <div className="segment-tabs project-tabs">{([{key:"workspace",label:"مساحة محاسب المشروع"},{key:"snapshot",label:"الملخص"},{key:"ledger",label:"دفتر المشروع"},{key:"trial",label:"ميزان المشروع"},{key:"cost",label:"دفتر التكلفة"},{key:"income",label:"قائمة الدخل"},{key:"position",label:"المركز المالي"},{key:"journals",label:"القيود"}] as const).map((item)=><button key={item.key} className={view===item.key?"active":""} onClick={()=>setView(item.key)}>{item.label}</button>)}</div>
    {view==="workspace"&&commit&&<AccountingOperations data={data} companyId={project.companyId} projectId={project.id} commit={commit} onJournal={setSelectedJournal}/>}
    {view==="snapshot"&&<><div className="metrics project-snapshot"><AccountingMetric label="إيراد العقد" value={formatMoney(project.contractValue,data.settings.currency)} note={`${project.progress}% إنجاز`} icon={FileBarChart}/><AccountingMetric label="الإيراد المعتمد" value={formatMoney(position.certifiedRevenue,data.settings.currency)} note="مستخلصات العملاء" icon={WalletCards}/><AccountingMetric label="التكلفة المحاسبية" value={formatMoney(reconciliation.accountingCost,data.settings.currency)} note="قيود المشروع المرحلة" icon={Landmark}/><AccountingMetric label="التكلفة الملتزم بها" value={formatMoney(committedCost,data.settings.currency)} note="أوامر الشراء المفتوحة" icon={ClipboardCheck}/><AccountingMetric label="الربح الإجمالي" value={formatMoney(income.grossProfit,data.settings.currency)} note={`${(income.revenue?income.grossProfit/income.revenue*100:0).toFixed(1)}%`} icon={FileBarChart} good={income.grossProfit>=0}/><AccountingMetric label="الربح المتوقع" value={formatMoney(forecastProfit,data.settings.currency)} note={`${(project.contractValue?forecastProfit/project.contractValue*100:0).toFixed(1)}%`} icon={FileBarChart} good={forecastProfit>=0}/><AccountingMetric label="ذمم العملاء" value={formatMoney(position.customerReceivable,data.settings.currency)} note="رصيد مستحق" icon={WalletCards}/><AccountingMetric label="الاحتجازات" value={formatMoney(position.customerRetention,data.settings.currency)} note="احتجازات العملاء" icon={WalletCards}/></div><ReconciliationCard reconciliation={reconciliation} currency={data.settings.currency}/></>}
    {view==="ledger"&&<ProjectLedgerView projectId={project.id} data={data} onJournal={(number)=>setSelectedJournal(data.journalEntries.find((entry)=>entry.number===number))}/>} 
    {view==="trial"&&<ProjectTrialView projectId={project.id} data={data}/>} 
    {view==="cost"&&<ProjectCostView projectId={project.id} data={data}/>} 
    {view==="income"&&<IncomeStatement data={{revenue:income.revenue,directCosts:income.materialCost+income.laborCost+income.equipmentCost+income.subcontractorCost+income.directExpenses,grossProfit:income.grossProfit,expenses:income.allocatedOverhead,operatingProfit:income.operatingProfit}} currency={data.settings.currency} breakdown={income}/>} 
    {view==="position"&&<FinancialPositionView position={position} currency={data.settings.currency}/>} 
    {view==="journals"&&<ProjectJournals entries={projectJournalEntries(project.id,data)} currency={data.settings.currency} onJournal={setSelectedJournal}/>} 
    <JournalDetails journal={selectedJournal} data={data} onClose={()=>setSelectedJournal(undefined)}/>
  </>;
}

function GeneralLedger({entries,currency,projects,onJournal}:{entries:JournalEntry[];currency:string;projects:Project[];onJournal:(entry:JournalEntry)=>void}){const[accountCode,setAccountCode]=useState("all");const[projectId,setProjectId]=useState("all");const[from,setFrom]=useState("");const[to,setTo]=useState("");const accounts=[...new Map(entries.flatMap(entry=>entry.lines).map(line=>[line.accountCode,`${line.accountCode} — ${line.accountName}`])).entries()];const rows=buildGeneralLedger(entries,projects,{accountCode:accountCode==="all"?undefined:accountCode,projectId:projectId==="all"?undefined:projectId,from:from||undefined,to:to||undefined});const periodDebit=rows.reduce((sum,row)=>sum+row.debit,0),periodCredit=rows.reduce((sum,row)=>sum+row.credit,0);const columns:ColumnDef<(typeof rows)[number]>[]=[{accessorKey:"date",header:"التاريخ"},{accessorKey:"journal",header:"القيد",cell:x=><button className="link-button" onClick={()=>onJournal(x.row.original.entry)}>{x.getValue<string>()}</button>},{accessorKey:"account",header:"الحساب"},{accessorKey:"description",header:"البيان"},{accessorKey:"debit",header:"مدين",cell:x=>formatMoney(x.getValue<number>(),currency)},{accessorKey:"credit",header:"دائن",cell:x=>formatMoney(x.getValue<number>(),currency)},{accessorKey:"balance",header:"رصيد الحساب الجاري",cell:x=>formatMoney(x.getValue<number>(),currency)},{id:"project",header:"المشروع",cell:x=>x.row.original.project?`${x.row.original.project.code} — ${x.row.original.project.name}`:"على مستوى الشركة"},{accessorKey:"reference",header:"المرجع"}];return <><div className="ledger-filters"><label>الحساب<select className="select" value={accountCode} onChange={event=>setAccountCode(event.target.value)}><option value="all">كل الحسابات</option>{accounts.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>المشروع<select className="select" value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="all">كل المشروعات</option>{projects.map(project=><option key={project.id} value={project.id}>{project.code} — {project.name}</option>)}</select></label><label>من<input className="input" type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>إلى<input className="input" type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></div><div className="ledger-summary"><span>حركة مدين <strong>{formatMoney(periodDebit,currency)}</strong></span><span>حركة دائن <strong>{formatMoney(periodCredit,currency)}</strong></span><span>الفرق <strong>{formatMoney(periodDebit-periodCredit,currency)}</strong></span></div><DataTable data={rows} columns={columns} searchPlaceholder="بحث بالحساب أو المشروع أو المرجع..."/></>}
function TrialBalance({rows,currency}:{rows:ReturnType<typeof calculateTrialBalance>;currency:string}){const columns:ColumnDef<(typeof rows)[number]>[]=[{accessorKey:"account",header:"كود الحساب"},{accessorKey:"accountName",header:"اسم الحساب"},{accessorKey:"debit",header:"إجمالي مدين",cell:x=>formatMoney(x.getValue<number>(),currency)},{accessorKey:"credit",header:"إجمالي دائن",cell:x=>formatMoney(x.getValue<number>(),currency)},{accessorKey:"balance",header:"الرصيد",cell:x=>formatMoney(x.getValue<number>(),currency)}];return <DataTable data={rows} columns={columns}/>}
function ChartOfAccounts({data,companyId,commit}:{data:ErpData;companyId:string;commit:Commit}){
  const accounts=data.chartOfAccounts.filter(account=>account.companyId===companyId);
  const[showForm,setShowForm]=useState(accounts.length===0);
  const[form,setForm]=useState({code:"",name:"",nameEn:"",type:"asset" as AccountType,parentCode:""});
  const missingCodes=[...new Set(data.journalEntries.filter(entry=>entry.companyId===companyId&&entry.status==="posted").flatMap(entry=>entry.lines.map(line=>line.accountCode)).filter(code=>!accounts.some(account=>account.code===code)))];
  const update=(account:ChartOfAccount,patch:Partial<ChartOfAccount>)=>commit({...data,chartOfAccounts:data.chartOfAccounts.map(item=>item.id===account.id?{...item,...patch,updatedAt:new Date().toISOString()}:item)},`تم تحديث تصنيف الحساب ${account.code} وإعادة احتساب القوائم`);
  const addAccount=(event:React.FormEvent)=>{event.preventDefault();const code=form.code.trim(),name=form.name.trim();if(!code||!name||accounts.some(account=>account.code===code))return;const now=new Date().toISOString();const account=withAccountClassification({id:uid("acc"),companyId,code,name,nameEn:form.nameEn.trim(),type:form.type,parentCode:form.parentCode||undefined,isControl:false,active:true,createdAt:now,updatedAt:now});commit({...data,chartOfAccounts:[...data.chartOfAccounts,account]},`تمت إضافة الحساب ${code}`);setForm({code:"",name:"",nameEn:"",type:"asset",parentCode:""});setShowForm(false);};
  const columns:ColumnDef<ChartOfAccount>[]=[{accessorKey:"code",header:"الحساب",cell:x=><strong>{x.row.original.code} — {x.row.original.name}</strong>},{accessorKey:"type",header:"النوع",cell:x=><span className="badge">{x.getValue<string>()}</span>},{accessorKey:"statementType",header:"القائمة المالية",cell:x=>{const account=x.row.original;const classification=inferAccountClassification(account);return <select aria-label={`القائمة المالية ${account.code}`} className="input account-classification-select" value={account.statementType??classification.statementType} onChange={event=>{const statementType=event.target.value as NonNullable<ChartOfAccount["statementType"]>;update(account,{statementType,statementSection:validSections(statementType)[0][0]});}}><option value="balance-sheet">قائمة المركز المالي</option><option value="income-statement">قائمة الدخل</option></select>}},{accessorKey:"statementSection",header:"بند العرض",cell:x=>{const account=x.row.original;const classification=inferAccountClassification(account);const statementType=account.statementType??classification.statementType;return <select aria-label={`بند العرض ${account.code}`} className="input account-classification-select" value={account.statementSection??classification.statementSection} onChange={event=>update(account,{statementSection:event.target.value})}>{validSections(statementType).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>}},{accessorKey:"normalBalance",header:"طبيعة الرصيد",cell:x=>{const account=x.row.original;return <select aria-label={`طبيعة الرصيد ${account.code}`} className="input account-classification-select" value={account.normalBalance??inferAccountClassification(account).normalBalance} onChange={event=>update(account,{normalBalance:event.target.value as NonNullable<ChartOfAccount["normalBalance"]>})}><option value="debit">مدين</option><option value="credit">دائن</option></select>}},{accessorKey:"cashFlowCategory",header:"التدفقات النقدية",cell:x=>{const account=x.row.original;return <select aria-label={`التدفقات النقدية ${account.code}`} className="input account-classification-select" value={account.cashFlowCategory??inferAccountClassification(account).cashFlowCategory} onChange={event=>update(account,{cashFlowCategory:event.target.value as NonNullable<ChartOfAccount["cashFlowCategory"]>})}><option value="operating">تشغيلي</option><option value="investing">استثماري</option><option value="financing">تمويلي</option><option value="non-cash">غير نقدي</option></select>}}];
  return <><div className="section-command"><div className="notice account-classification-help"><CheckCircle2 size={18}/><div><strong>تصنيف القوائم قابل للتحكم</strong><span>الحسابات القديمة تُصنّف محليًا. أي تعديل يعيد احتساب الموازين والقوائم فورًا دون تغيير القيود.</span></div></div><button className="btn btn-primary" onClick={()=>setShowForm(value=>!value)}>{showForm?"إلغاء":"+ إضافة حساب"}</button></div>{showForm&&<form className="card accounting-account-form" onSubmit={addAccount}><label>كود الحساب<input aria-label="كود الحساب الجديد" className="input" value={form.code} onChange={event=>setForm({...form,code:event.target.value})} required/></label><label>الاسم بالعربية<input aria-label="اسم الحساب بالعربية" className="input" value={form.name} onChange={event=>setForm({...form,name:event.target.value})} required/></label><label>الاسم بالإنجليزية<input aria-label="اسم الحساب بالإنجليزية" className="input" value={form.nameEn} onChange={event=>setForm({...form,nameEn:event.target.value})}/></label><label>نوع الحساب<select aria-label="نوع الحساب الجديد" className="select" value={form.type} onChange={event=>setForm({...form,type:event.target.value as AccountType})}>{(["asset","liability","equity","revenue","cost","expense"] as AccountType[]).map(type=><option key={type} value={type}>{accountTypeLabel(type)}</option>)}</select></label><label>الحساب الأب<select aria-label="الحساب الأب" className="select" value={form.parentCode} onChange={event=>setForm({...form,parentCode:event.target.value})}><option value="">بدون حساب أب</option>{accounts.map(account=><option key={account.id} value={account.code}>{account.code} — {account.name}</option>)}</select></label><button className="btn btn-primary" type="submit">حفظ الحساب</button></form>}{missingCodes.length>0&&<div className="notice accounting-warning"><AlertTriangle size={18}/><div><strong>قيود مرحلة تستخدم حسابات غير موجودة في الدليل</strong><span>{missingCodes.join("، ")} — أضف هذه الحسابات أو صحح القيد حتى لا تختفي من القوائم.</span></div></div>}<DataTable data={accounts} columns={columns} searchPlaceholder="بحث بكود الحساب أو اسمه..."/></>;
}
function accountTypeLabel(type:AccountType){return({asset:"أصل",liability:"التزام",equity:"حقوق ملكية",revenue:"إيراد",cost:"تكلفة مشروع",expense:"مصروف"})[type]}
function MappingEditor({data,companyId,commit}:{data:ErpData;companyId:string;commit:Commit}){const mapping=data.accountingMappings.find(item=>item.companyId===companyId);if(!mapping)return <div className="notice"><AlertTriangle size={18}/>لا يوجد ربط محاسبي لهذه الشركة.</div>;const fields:[keyof AccountingMapping,string][]=[["customerControl","حساب مراقبة العملاء"],["supplierControl","حساب مراقبة الموردين"],["subcontractorControl","حساب مراقبة مقاولي الباطن"],["inventory","حساب المخزون"],["materialCost","حساب تكلفة المواد"],["laborCost","حساب تكلفة العمالة"],["equipmentCost","حساب تكلفة المعدات"],["subcontractorCost","حساب تكلفة مقاولي الباطن"],["siteExpense","حساب مصروفات الموقع"],["projectRevenue","حساب إيرادات المشروعات"],["wip","حساب أعمال تحت التنفيذ"],["retentionReceivable","احتجازات مستحقة"],["retentionPayable","احتجازات دائنة"],["cash","النقدية"],["bank","البنوك"],["vatOutput","ضريبة القيمة المضافة المستحقة (VAT)"],["vatInput","ضريبة القيمة المضافة القابلة للخصم (VAT)"]];const accounts=data.chartOfAccounts.filter(account=>account.companyId===companyId&&account.active);const update=(key:keyof AccountingMapping,value:string)=>commit({...data,accountingMappings:data.accountingMappings.map(item=>item.id===mapping.id?{...item,[key]:value,updatedAt:new Date().toISOString()}:item)},"تم تحديث الربط المحاسبي");return <div className="card"><div className="card-head"><div><h3>الربط المحاسبي حسب الشركة</h3><p>تستخدم القيود الآلية هذه الإعدادات القابلة للتعديل.</p></div><span className="badge active">قابل للضبط</span></div><div className="mapping-grid">{fields.map(([key,label])=><div className="field" key={key}><label>{label}</label><select className="input" value={String(mapping[key])} onChange={event=>update(key,event.target.value)}>{accounts.map(account=><option key={account.id} value={account.code}>{account.code} — {account.name}</option>)}</select></div>)}</div></div>}
function ProjectLedgerView({projectId,data,onJournal}:{projectId:string;data:ErpData;onJournal:(number:string)=>void}){const rows=projectLedger(projectId,data);const columns:ColumnDef<(typeof rows)[number]>[]=[{accessorKey:"date",header:"التاريخ"},{accessorKey:"journalNumber",header:"القيد",cell:x=><button className="link-button" onClick={()=>onJournal(x.getValue<string>())}>{x.getValue<string>()}</button>},{id:"account",header:"الحساب",cell:x=>`${x.row.original.accountCode} — ${x.row.original.accountName}`},{accessorKey:"description",header:"البيان"},{accessorKey:"debit",header:"مدين",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"credit",header:"دائن",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"balance",header:"الأثر التراكمي",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"costCode",header:"Cost Code"},{accessorKey:"boq",header:"BOQ"},{accessorKey:"source",header:"المصدر"},{accessorKey:"reference",header:"المرجع"}];return <DataTable data={rows} columns={columns}/>} 
function ProjectTrialView({projectId,data}:{projectId:string;data:ErpData}){const rows=projectTrialBalance(projectId,data);const columns:ColumnDef<(typeof rows)[number]>[]=[{accessorKey:"accountCode",header:"كود الحساب"},{accessorKey:"accountName",header:"اسم الحساب"},{accessorKey:"openingDebit",header:"افتتاحي مدين",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"openingCredit",header:"افتتاحي دائن",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"periodDebit",header:"حركة مدين",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"periodCredit",header:"حركة دائن",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"closingDebit",header:"ختامي مدين",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)},{accessorKey:"closingCredit",header:"ختامي دائن",cell:x=>formatMoney(x.getValue<number>(),data.settings.currency)}];return <DataTable data={rows} columns={columns}/>} 
function ProjectCostView({projectId,data}:{projectId:string;data:ErpData}){const rows=projectCostLedger(projectId,data);const columns:ColumnDef<(typeof rows)[number]>[]=[{accessorKey:"date",header:"التاريخ"},{accessorKey:"costType",header:"نوع التكلفة"},{accessorKey:"costCode",header:"Cost Code"},{accessorKey:"boq",header:"BOQ"},{accessorKey:"source",header:"المصدر"},{accessorKey:"reference",header:"المستند"},{accessorKey:"amount",header:"القيمة",cell:x=><strong>{formatMoney(x.getValue<number>(),data.settings.currency)}</strong>}];return <DataTable data={rows} columns={columns}/>} 
function ProjectJournals({entries,currency,onJournal}:{entries:JournalEntry[];currency:string;onJournal:(entry:JournalEntry)=>void}){const columns:ColumnDef<JournalEntry>[]=[{accessorKey:"date",header:"التاريخ"},{accessorKey:"number",header:"رقم القيد",cell:x=><button className="link-button" onClick={()=>onJournal(x.row.original)}>{x.getValue<string>()}</button>},{accessorKey:"description",header:"البيان"},{accessorKey:"sourceModule",header:"المصدر"},{accessorKey:"sourceNumber",header:"المستند"},{accessorKey:"automatic",header:"النوع",cell:x=><span className="badge">{x.getValue<boolean>()?"آلي":"يدوي"}</span>},{id:"amount",header:"القيمة",cell:x=>formatMoney(x.row.original.lines.reduce((sum,line)=>sum+line.debit,0),currency)},{accessorKey:"status",header:"الحالة",cell:x=><span className={`badge ${x.getValue<string>()}`}>{x.getValue<string>()}</span>}];return <DataTable data={entries} columns={columns}/>}
function IncomeStatement({data,currency,breakdown}:{data:{revenue:number;directCosts:number;grossProfit:number;expenses:number;operatingProfit:number};currency:string;breakdown?:ReturnType<typeof projectIncomeStatement>}){const rows=breakdown?[{label:"إيرادات المشروع",amount:data.revenue,kind:"revenue"},{label:"510100 — تكلفة المواد",amount:-breakdown.materialCost,kind:"cost"},{label:"510200 — تكلفة العمالة",amount:-breakdown.laborCost,kind:"cost"},{label:"510300 — تكلفة المعدات",amount:-breakdown.equipmentCost,kind:"cost"},{label:"510400 — تكلفة مقاولي الباطن",amount:-breakdown.subcontractorCost,kind:"cost"},{label:"510600 — مصروفات الموقع",amount:-breakdown.directExpenses,kind:"cost"},{label:"مجمل ربح المشروع",amount:data.grossProfit,kind:"total"},{label:"المصروفات غير المباشرة الموزعة",amount:-data.expenses,kind:"cost"},{label:"الربح التشغيلي",amount:data.operatingProfit,kind:"final"}]:[{label:"إيرادات عقود المشاريع",amount:data.revenue,kind:"revenue"},{label:"تكاليف المشاريع المباشرة",amount:-data.directCosts,kind:"cost"},{label:"مجمل ربح الشركة",amount:data.grossProfit,kind:"total"},{label:"المصروفات الإدارية والعامة",amount:-data.expenses,kind:"cost"},{label:"صافي الربح التشغيلي",amount:data.operatingProfit,kind:"final"}];return <div className="card statement-card"><div className="card-head"><div><h3>قائمة الدخل</h3><p>من القيود المرحلة فقط</p></div></div><div className="statement-lines">{rows.map((row)=><div key={row.label} className={row.kind}><span>{row.label}</span><strong>{formatMoney(row.amount,currency)}</strong></div>)}</div></div>}
function FinancialPositionView({position,currency}:{position:ReturnType<typeof projectFinancialPosition>;currency:string}){const groups=[{title:"الأصول والمستحقات",items:[["ذمم العملاء",position.customerReceivable],["احتجازات العملاء",position.customerRetention],["نقدية وبنوك المشروع",position.projectCash],["أعمال تحت التنفيذ",position.wip],["أعمال غير مفوترة",position.unbilledWork]]},{title:"الالتزامات",items:[["ذمم الموردين",position.supplierPayables],["ذمم مقاولي الباطن",position.subcontractorPayables],["التكاليف المستحقة",position.accruedCosts],["الارتباطات المفتوحة",position.commitments]]},{title:"مؤشرات التنفيذ",items:[["الإيراد المعتمد",position.certifiedRevenue],["دفعات مقدمة",position.advances]]}];return <div className="position-grid">{groups.map(group=><div className="card" key={group.title}><div className="card-head"><h3>{group.title}</h3></div><div className="position-lines">{group.items.map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{formatMoney(Number(value),currency)}</strong></div>)}</div></div>)}</div>}
function ReconciliationCard({reconciliation,currency}:{reconciliation:ReturnType<typeof projectReconciliation>;currency:string}){const clean=Math.abs(reconciliation.difference)<.01;return <div className={`reconciliation ${clean?"clean":"issue"}`}><div className="reconciliation-icon">{clean?<CheckCircle2/>:<AlertTriangle/>}</div><div><span>تسوية تكلفة المشروع</span><h4>{clean?"دفتر التكلفة مطابق للدفتر المحاسبي":"يوجد فرق يحتاج التحقيق"}</h4><p>الدفتر المحاسبي: {formatMoney(reconciliation.accountingCost,currency)} · دفتر التكلفة: {formatMoney(reconciliation.costLedger,currency)}</p></div><strong>{formatMoney(reconciliation.difference,currency)}</strong></div>}
function ClosingChecklist({data,periodId,commit}:{data:ErpData;periodId:string;commit:Commit}){const period=data.fiscalPeriods.find((item)=>item.id===periodId);if(!period)return <AccountingEmpty title="لا توجد فترة محاسبية محددة"/>;const tasks=period.closingTasks??[];const toggle=(taskId:string)=>commit({...data,fiscalPeriods:data.fiscalPeriods.map((item)=>item.id===periodId?{...item,closingTasks:(item.closingTasks??[]).map((task)=>task.id===taskId?{...task,completed:!task.completed}:task),updatedAt:new Date().toISOString()}:item)},"تم تحديث قائمة الإقفال");return <div className="card"><div className="card-head"><div><h3>إقفال نهاية الشهر — {period.name}</h3><p>{tasks.filter((task)=>task.completed).length} / {tasks.length} مهام مكتملة</p></div><span className={`badge ${period.status==="open"?"draft":"posted"}`}>{period.status==="open"?"مفتوحة":period.status==="soft-closed"?"مقفلة مبدئيًا":"مقفلة"}</span></div><div className="closing-list">{tasks.map((task)=><label key={task.id}><input type="checkbox" checked={task.completed} onChange={()=>toggle(task.id)}/><span>{task.label}</span>{task.completed&&<CheckCircle2 size={17}/>}</label>)}</div></div>}
function YearEndClosing({data,companyId,fiscalYear,commit}:{data:ErpData;companyId:string;fiscalYear:number;commit:Commit}){const[error,setError]=useState("");const execute=()=>{try{setError("");commit(closeFiscalYear(data,companyId,fiscalYear),`تم إقفال ${fiscalYear} وترحيل الأرصدة وفتح ${fiscalYear+1}`);}catch(cause){setError(cause instanceof Error?cause.message:"تعذر تنفيذ إقفال السنة");}};return <div className="card" style={{marginTop:16}}><div className="card-head"><div><h3>إقفال السنة المالية {fiscalYear}</h3><p>الإقفالات النهائية ← تحويل الربح ← ترحيل الحسابات الدائمة ← قيد افتتاحي وفترات السنة الجديدة</p></div><button className="btn btn-primary" onClick={execute}>تنفيذ إقفال السنة</button></div>{error&&<div className="notice"><AlertTriangle size={17}/>{error}</div>}</div>}
function AccountingEmpty({title,action,onAction}:{title:string;action?:string;onAction?:()=>void}){return <div className="accounting-empty"><Landmark/><strong>{title}</strong><p>يمكنك المتابعة بأمان عند جاهزية البيانات.</p>{action&&onAction&&<button className="btn btn-primary" onClick={onAction}>{action}</button>}</div>}
function JournalDetails({journal,data,onClose,onReverse}:{journal?:JournalEntry;data:ErpData;onClose:()=>void;onReverse?:(entry:JournalEntry)=>void}){if(!journal)return null;const project=data.projects.find((item)=>item.id===journal.projectId);return <Modal open title={`${journal.number} — ${journal.sourceType}`} onClose={onClose}><div className="dialog-body"><div className="journal-summary"><div><span>الشركة</span><strong>{data.companies.find((company)=>company.id===journal.companyId)?.name??"—"}</strong></div><div><span>المشروع</span><strong>{project?`${project.code} — ${project.name}`:"Company Level"}</strong></div><div><span>المصدر</span><strong>{journal.sourceModule} · {journal.sourceNumber}</strong></div><div><span>الحالة</span><strong className={`badge ${journal.status}`}>{journal.status}</strong></div></div><div className="table-scroll"><table><thead><tr><th>الحساب</th><th>البيان</th><th>Cost Code</th><th>BOQ</th><th>مدين</th><th>دائن</th></tr></thead><tbody>{journal.lines.map((line,index)=><tr key={`${line.accountCode}-${index}`}><td><strong>{line.accountCode} — {line.accountName}</strong></td><td>{line.description}</td><td>{line.costCode??"—"}</td><td>{line.boqItemId?data.boqItems.find((item)=>item.id===line.boqItemId)?.code??line.boqItemId:"—"}</td><td>{formatMoney(line.debit,data.settings.currency)}</td><td>{formatMoney(line.credit,data.settings.currency)}</td></tr>)}</tbody></table></div><div className="audit-trail"><h4>Audit Trail</h4>{journal.auditTrail.map((event,index)=><div key={`${event.action}-${index}`}><span className="audit-dot"/><strong>{event.action}</strong><span>{event.user}</span><time>{new Date(event.timestamp).toLocaleString("ar-EG")}</time></div>)}</div></div><div className="dialog-foot"><button className="btn btn-secondary" onClick={onClose}>إغلاق</button>{onReverse&&journal.status==="posted"&&!journal.reversedFromId&&<button className="btn btn-danger" onClick={()=>onReverse(journal)}><RotateCcw size={15}/>عكس القيد</button>}</div></Modal>}
function AccountingMetric({label,value,note,icon:Icon,good}:{label:string;value:string;note:string;icon:React.ElementType;good?:boolean}){return <div className={`metric ${good?"good":""}`}><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon size={18}/></span></div><strong>{value}</strong><small>{note}</small></div>}
function ControlPanel({title,icon:Icon,items}:{title:string;icon:React.ElementType;items:{label:string;value:string;danger?:boolean}[]}){return <div className="card"><div className="card-head"><div><h3>{title}</h3><p>فحص آلي لسلامة الدورة</p></div><Icon size={19} color="#2878a8"/></div><div className="control-list">{items.map(item=><div key={item.label}><span>{item.label}</span><strong className={item.danger&&item.value!=="0"?"danger-text":""}>{item.value}</strong></div>)}</div></div>}
function isBalanced(entry:JournalEntry){const debit=entry.lines.reduce((sum,line)=>sum+line.debit,0);const credit=entry.lines.reduce((sum,line)=>sum+line.credit,0);return Math.abs(debit-credit)<.01}
function findUnpostedSources(data:ErpData,companyId?:string){const belongs=(projectId?:string)=>!companyId||data.projects.some(project=>project.id===projectId&&project.companyId===companyId);const posted=new Set(data.journalEntries.filter(entry=>!companyId||entry.companyId===companyId).map((entry)=>entry.sourceNumber));return [...data.inventoryMovements.filter((item)=>belongs(item.projectId)&&item.status==="posted"&&(item.type==="issue"||item.type==="receipt")).map((item)=>({reference:item.number,module:"المخزون",description:item.material})),...data.expenses.filter((item)=>belongs(item.projectId)&&item.status==="posted").map((item)=>({reference:item.number,module:"المصروفات",description:item.description})),...data.certificates.filter((item)=>belongs(item.projectId)&&item.status==="posted").map((item)=>({reference:item.number,module:"المستخلصات",description:item.type==="customer"?"مستخلص عميل":"مستخلص مقاول باطن"}))].filter((item)=>!posted.has(item.reference))}
