"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- compact tree-state toggle intentionally uses Set mutation return values */

import ExcelJS from "exceljs";
import { useState } from "react";
import { AlertTriangle, CheckCircle2, Download, Printer, Scale } from "lucide-react";
import { Modal } from "@/components/shared/modal";
import { accountJournalLines, balanceSheet, cashFlowStatement, detailedTrialBalance, equityStatement, financialReportingIssues, incomeStatement, type FinancialFilters } from "@/services/financial-statements";
import { useUiStore } from "@/store/ui-store";
import type { ErpData } from "@/types/erp";
import { formatMoney, localDateInputValue } from "@/utils/format";

export type FinancialReport = "center" | "income" | "balance" | "cash-flow" | "equity" | "trial" | "adjusted-trial" | "post-closing-trial" | "project-position";
type T = (ar: string, en: string) => string;

const reportNames: Record<FinancialReport, [string, string]> = {
  center: ["القوائم المالية", "Financial Statements"], income: ["قائمة الدخل", "Income Statement"], balance: ["الميزانية العمومية", "Balance Sheet"], "cash-flow": ["قائمة التدفقات النقدية", "Cash Flow Statement"], equity: ["قائمة التغير في حقوق الملكية", "Statement of Changes in Equity"], trial: ["ميزان المراجعة", "Trial Balance"], "adjusted-trial": ["ميزان المراجعة المعدل", "Adjusted Trial Balance"], "post-closing-trial": ["ميزان المراجعة بعد الإقفال", "Post-closing Trial Balance"], "project-position": ["المركز المالي للمشروع", "Project Financial Position"],
};

export function FinancialStatementsCenter({ data, companyId, initialReport = "center", t }: { data: ErpData; companyId: string; initialReport?: FinancialReport; t: T }) {
  const today = localDateInputValue(); const [report, setReport] = useState<FinancialReport>(initialReport); const [projectId, setProjectId] = useState("all"); const [from, setFrom] = useState(`${new Date().getFullYear()}-01-01`); const [to, setTo] = useState(today); const [comparison, setComparison] = useState(true); const [drill, setDrill] = useState<{ title: string; codes: string[] }>();
  const setModule = useUiStore((state) => state.setModule);
  const filters: FinancialFilters = { companyId, projectId: projectId === "all" ? undefined : projectId, from, to };
  const projects = data.projects.filter((project) => project.companyId === companyId);
  const title = reportNames[report]; const company = data.companies.find((item) => item.id === companyId); const project = projects.find((item) => item.id === projectId);
  const previousFilters = previousPeriod(filters);
  const reportingIssues = financialReportingIssues(data, filters);
  const pendingJournals = data.journalEntries.filter((entry) => entry.companyId === companyId && ["draft", "reviewed"].includes(entry.status) && entry.date >= from && entry.date <= to).length;
  const print = () => window.print();
  const exportExcel = async () => { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet(title[1]); sheet.addRows([["SiteCost ERP"], [company?.name ?? ""], [t(...title)], [project ? `${project.code} — ${project.name}` : t("كل المشروعات", "All projects")], [`${from} — ${to}`], []]); const rows = exportRows(report, data, filters, t); sheet.addRows(rows); sheet.getColumn(1).width = 34; sheet.getColumn(2).width = 20; [1, 3, 7].forEach((row) => { sheet.getRow(row).font = { bold: true }; }); const buffer = await book.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([buffer])); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${report}-${to}.xlsx`; anchor.click(); URL.revokeObjectURL(url); };
  if (!data.chartOfAccounts.some((account) => account.companyId === companyId)) return <div className="accounting-empty"><Scale/><strong>{t("لم يتم إعداد دليل الحسابات بعد", "The chart of accounts has not been configured")}</strong><button className="btn btn-primary" onClick={() => setModule("chart-accounts")}>{t("+ إعداد دليل الحسابات", "+ Set up chart of accounts")}</button></div>;
  if (!data.journalEntries.some((entry) => entry.companyId === companyId && entry.status === "posted")) return <div className="accounting-empty"><Scale/><strong>{t("لا توجد بيانات مالية مرحّلة كافية لإعداد التقرير", "There is not enough posted financial data to prepare this report")}</strong></div>;
  return <div className="financial-center">
    <div className="financial-print-head"><strong>SiteCost ERP</strong><span>{company?.name}</span><h2>{t(...title)}</h2><span>{project ? `${project.code} — ${project.name}` : t("كل المشروعات", "All projects")} · {from} — {to}</span><small>{t("تاريخ الطباعة", "Printed")}: {new Date().toLocaleString()}</small></div>
    <div className="report-command"><div><span>{t("التقارير المالية", "FINANCIAL REPORTING")}</span><h3>{t(...title)}</h3><p>{t("مصدر الأرقام: القيود اليومية المرحلة وتصنيف دليل الحسابات فقط.", "Figures come only from posted journal lines and chart classification.")}</p></div><div className="actions"><button className="btn btn-secondary" onClick={print}><Printer size={15}/>{t("طباعة", "Print")}</button><button className="btn btn-secondary" onClick={exportExcel}><Download size={15}/>Excel</button></div></div>
    {pendingJournals>0&&<div className="notice accounting-warning"><AlertTriangle size={17}/><div><strong>{t(`${pendingJournals} قيدًا داخل الفترة لم يُرحّل بعد`, `${pendingJournals} journals in this period are not posted`)}</strong><span>{t("الأرقام لن تظهر قبل إكمال Review ثم Post من سجل القيود.", "Figures will not appear until Review and Post are completed in the journal register.")}</span></div></div>}
    {reportingIssues.length>0&&<div className="notice accounting-warning"><AlertTriangle size={17}/><div><strong>{t("حسابات مستخدمة تحتاج تصحيحًا في دليل الحسابات", "Used accounts require chart-of-accounts correction")}</strong><span>{reportingIssues.map(issue=>`${issue.accountCode} — ${issue.accountName}`).join("، ")}</span></div><button className="btn btn-secondary compact" onClick={()=>setModule("chart-accounts")}>{t("فتح دليل الحسابات", "Open chart of accounts")}</button></div>}
    <div className="statement-nav">{(["income", "balance", "cash-flow", "equity", "trial", "adjusted-trial", "post-closing-trial"] as FinancialReport[]).map((key) => <button className={report === key ? "active" : ""} key={key} onClick={() => setReport(key)}>{t(...reportNames[key])}</button>)}</div>
    <div className="report-filters"><label>{t("الشركة", "Company")}<select className="input" value={companyId} disabled><option>{company?.name}</option></select></label><label>{t("المشروع", "Project")}<select className="input" value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="all">{t("كل المشروعات — قوائم الشركة", "All projects — Company statements")}</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></label><label>{report === "balance" ? t("حتى تاريخ", "As of") : t("من تاريخ", "From")}<input className="input" type="date" value={report === "balance" ? to : from} onChange={(event) => report === "balance" ? setTo(event.target.value) : setFrom(event.target.value)}/></label>{report !== "balance" && <label>{t("إلى تاريخ", "To")}<input className="input" type="date" value={to} onChange={(event) => setTo(event.target.value)}/></label>}<label className="comparison-check"><input type="checkbox" checked={comparison} onChange={(event) => setComparison(event.target.checked)}/>{t("مقارنة بالفترة السابقة", "Compare with previous period")}</label></div>
    {projectId !== "all" && report === "balance" && <div className="notice"><AlertTriangle size={17}/>{t("يعرض النظام المركز المالي للمشروع بدل ميزانية عمومية كاملة لأن بعض الأصول والخصوم لا تحمل بُعد المشروع.", "A project financial position is shown instead of a full balance sheet because not every asset and liability carries a project dimension.")}</div>}
    {(report === "center") && <ReportCards t={t} onSelect={setReport}/>} 
    {report === "income" && <IncomeView data={data} filters={filters} previous={comparison ? previousFilters : undefined} t={t} onDrill={(title, codes) => setDrill({ title, codes })}/>} 
    {report === "balance" && (projectId === "all" ? <BalanceView data={data} filters={{ ...filters, from: undefined }} t={t} onDrill={(label, codes) => setDrill({ title: label, codes })}/> : <ProjectPositionView data={data} filters={{ ...filters, from: undefined }} t={t} onDrill={(label, codes) => setDrill({ title: label, codes })}/>)}
    {report === "cash-flow" && <CashFlowView data={data} filters={filters} t={t}/>} 
    {report === "equity" && <EquityView data={data} filters={filters} t={t}/>} 
    {(["trial", "adjusted-trial", "post-closing-trial"] as FinancialReport[]).includes(report) && <TrialView data={data} filters={filters} mode={report === "adjusted-trial" ? "adjusted" : report === "post-closing-trial" ? "post-closing" : "trial"} t={t} onDrill={(label, codes) => setDrill({ title: label, codes })}/>} 
    <DrillDown open={drill} onClose={() => setDrill(undefined)} data={data} filters={filters} t={t}/>
  </div>;
}

function ReportCards({ t, onSelect }: { t: T; onSelect: (report: FinancialReport) => void }) { return <div className="report-card-grid">{(["income", "balance", "cash-flow", "equity"] as FinancialReport[]).map((report) => <button key={report} onClick={() => onSelect(report)}><Scale/><strong>{t(...reportNames[report])}</strong><span>{t("فتح التقرير والتحليل", "Open report and analysis")}</span></button>)}</div>; }
function IncomeView({ data, filters, previous, t, onDrill }: { data: ErpData; filters: FinancialFilters; previous?: FinancialFilters; t: T; onDrill: (label: string, codes: string[]) => void }) { const current = incomeStatement(data, filters); const prior = previous ? incomeStatement(data, previous) : undefined; const accounts = data.chartOfAccounts.filter((a) => a.companyId === filters.companyId); const rows = [["إيرادات المشروعات", "Project revenue", current.projectRevenue, "project-revenue"], ["إيرادات أخرى", "Other income", current.otherIncome, "other-income"], ["تكلفة المشروعات", "Project costs", -current.projectCost, "project-cost"], ["مجمل الربح", "Gross profit", current.grossProfit, "total"], ["المصروفات العمومية والإدارية", "General and administrative expenses", -current.operatingExpenses, "operating-expense"], ["الربح التشغيلي", "Operating profit", current.operatingProfit, "total"], ["إيرادات ومصروفات أخرى", "Other income and expenses", -current.otherExpenses, "other-expense"], ["صافي الربح", "Net profit", current.netProfit, "final"]] as const; return <Statement title={t("قائمة الدخل", "Income Statement")} rows={rows.map(([ar, en, amount, section]) => ({ label: t(ar, en), amount, previous: prior ? incomeValue(prior, section) : undefined, codes: accounts.filter((a) => a.statementSection === section).map((a) => a.code), kind: section }))} currency={data.settings.currency} onDrill={onDrill}/>; }
function incomeValue(value: ReturnType<typeof incomeStatement>, section: string) { const map: Record<string, number> = { "project-revenue": value.projectRevenue, "other-income": value.otherIncome, "project-cost": -value.projectCost, total: value.grossProfit, "operating-expense": -value.operatingExpenses, "other-expense": -value.otherExpenses, final: value.netProfit }; return map[section] ?? 0; }
function BalanceView({ data, filters, t, onDrill }: { data: ErpData; filters: FinancialFilters; t: T; onDrill: (label: string, codes: string[]) => void }) { const value = balanceSheet(data, filters); const sections = [["current-assets", "الأصول المتداولة", "Current assets"], ["non-current-assets", "الأصول غير المتداولة", "Non-current assets"], ["contra-assets", "مجمع الإهلاك", "Accumulated depreciation"], ["current-liabilities", "الخصوم", "Liabilities"], ["equity", "حقوق الملكية", "Equity"]] as const; const clean=Math.abs(value.difference)<.01;return <div className="financial-statement"><button className={`balance-validation ${clean ? "clean" : "issue"}`} disabled={clean} onClick={()=>onDrill(t("فرق الميزانية","Balance difference"),value.lines.flatMap(line=>line.accountCodes))}>{clean ? <CheckCircle2/> : <AlertTriangle/>}<div><strong>{t("الأصول = الخصوم + حقوق الملكية", "Assets = Liabilities + Equity")}</strong><span>{clean ? t("متوازن ✓", "Balanced ✓") : `${t("فرق الميزانية", "Balance difference")}: ${formatMoney(value.difference, data.settings.currency)}`}</span></div></button>{sections.map(([section, ar, en]) => <StatementSection key={section} title={t(ar, en)} lines={value.lines.filter((line) => section === "current-assets" ? ["current-assets", "cash", "banks"].includes(line.section) : line.section === section)} currency={data.settings.currency} onDrill={onDrill}/>)}<div className="statement-equation"><div><span>{t("إجمالي الأصول", "Total assets")}</span><strong>{formatMoney(value.assets, data.settings.currency)}</strong></div><b>=</b><div><span>{t("إجمالي الخصوم وحقوق الملكية", "Total liabilities and equity")}</span><strong>{formatMoney(value.liabilitiesAndEquity, data.settings.currency)}</strong></div></div></div>; }
function ProjectPositionView(props: Parameters<typeof BalanceView>[0]) { const { data, filters, t, onDrill } = props; const value = balanceSheet(data, filters); return <div className="financial-statement"><div className="statement-title"><h3>{t("المركز المالي للمشروع", "Project Financial Position")}</h3><p>{t("يعرض فقط الأرصدة التي تحمل بُعد المشروع.", "Only balances carrying the project dimension are included.")}</p></div>{["current-assets", "current-liabilities"].map((section) => <StatementSection key={section} title={section === "current-assets" ? t("الأصول والمستحقات المخصصة", "Allocated assets and receivables") : t("التزامات المشروع", "Project liabilities")} lines={value.lines.filter((line) => line.section === section)} currency={data.settings.currency} onDrill={onDrill}/>)}</div>; }
function CashFlowView({ data, filters, t }: { data: ErpData; filters: FinancialFilters; t: T }) { const value = cashFlowStatement(data, filters); const clean = Math.abs(value.difference) < .01; return <Statement title={t("قائمة التدفقات النقدية", "Cash Flow Statement")} rows={[{ label: t("التدفقات النقدية من الأنشطة التشغيلية", "Operating activities"), amount: value.operating }, { label: t("التدفقات النقدية من الأنشطة الاستثمارية", "Investing activities"), amount: value.investing }, { label: t("التدفقات النقدية من الأنشطة التمويلية", "Financing activities"), amount: value.financing }, { label: t("صافي التغير في النقدية", "Net change in cash"), amount: value.netChange, kind: "total" }, { label: t("رصيد النقدية أول الفترة", "Opening cash balance"), amount: value.openingCash }, { label: t("رصيد النقدية آخر الفترة", "Closing cash balance"), amount: value.closingCash, kind: "final" }, { label: clean ? t("مطابق للنقدية والبنوك في الميزانية ✓", "Reconciled to balance-sheet cash and banks ✓") : t("استثناء: فرق مع النقدية والبنوك", "Exception: cash reconciliation difference"), amount: value.difference, kind: clean ? "clean" : "issue" }]} currency={data.settings.currency}/>; }
function EquityView({ data, filters, t }: { data: ErpData; filters: FinancialFilters; t: T }) { const value = equityStatement(data, filters); return <Statement title={t("قائمة التغير في حقوق الملكية", "Statement of Changes in Equity")} rows={[{ label: t("رصيد أول الفترة", "Opening balance"), amount: value.opening }, { label: t("رأس المال والإضافات", "Capital and additions"), amount: value.capitalAdditions }, { label: t("صافي ربح الفترة", "Net profit"), amount: value.netProfit }, { label: t("توزيعات ومسحوبات", "Distributions and drawings"), amount: value.drawings }, { label: t("تعديلات", "Adjustments"), amount: value.adjustments }, { label: t("رصيد آخر الفترة", "Closing balance"), amount: value.closing, kind: "final" }]} currency={data.settings.currency}/>; }
function TrialView({ data, filters, mode, t, onDrill }: { data: ErpData; filters: FinancialFilters; mode: "trial" | "adjusted" | "post-closing"; t: T; onDrill: (label: string, codes: string[]) => void }) { const rows = detailedTrialBalance(data, filters, mode); const parents=new Set(rows.map(row=>row.parentCode).filter(Boolean));const [collapsed,setCollapsed]=useState<Set<string>>(new Set());const hidden=(row:typeof rows[number])=>{let parent=row.parentCode;while(parent){if(collapsed.has(parent))return true;parent=rows.find(item=>item.accountCode===parent)?.parentCode;}return false;};const depth=(row:typeof rows[number])=>{let count=0,parent=row.parentCode;while(parent){count++;parent=rows.find(item=>item.accountCode===parent)?.parentCode;}return count;};const detailRows=rows.filter(row=>!parents.has(row.accountCode));const total = (key: keyof typeof rows[number]) => detailRows.reduce((sum, row) => sum + Number(row[key]), 0); return <div className="card table-card"><div className="table-scroll"><table><thead><tr><th>{t("كود الحساب", "Account code")}</th><th>{t("اسم الحساب", "Account name")}</th><th>{t("أول المدة مدين", "Opening debit")}</th><th>{t("أول المدة دائن", "Opening credit")}</th><th>{t("حركة مدين", "Period debit")}</th><th>{t("حركة دائن", "Period credit")}</th><th>{t("آخر المدة مدين", "Closing debit")}</th><th>{t("آخر المدة دائن", "Closing credit")}</th></tr></thead><tbody>{rows.filter(row=>!hidden(row)).map((row) => <tr key={row.accountCode} className={parents.has(row.accountCode)?"account-group":""}><td><span style={{paddingInlineStart:depth(row)*16}}>{parents.has(row.accountCode)&&<button className="tree-toggle" onClick={()=>setCollapsed(current=>{const next=new Set(current);next.has(row.accountCode)?next.delete(row.accountCode):next.add(row.accountCode);return next;})}>{collapsed.has(row.accountCode)?"+":"−"}</button>}<button className="link-button" onClick={() => onDrill(`${row.accountCode} — ${row.accountName}`, [row.accountCode])}>{row.accountCode}</button></span></td><td>{row.accountName}</td>{(["openingDebit", "openingCredit", "periodDebit", "periodCredit", "closingDebit", "closingCredit"] as const).map((key) => <td key={key}>{formatMoney(row[key], data.settings.currency)}</td>)}</tr>)}</tbody><tfoot><tr><th colSpan={2}>{t("الإجمالي", "Total")}</th>{(["openingDebit", "openingCredit", "periodDebit", "periodCredit", "closingDebit", "closingCredit"] as const).map((key) => <th key={key}>{formatMoney(total(key), data.settings.currency)}</th>)}</tr></tfoot></table></div></div>; }
function Statement({ title, rows, currency, onDrill }: { title: string; rows: { label: string; amount: number; previous?: number; codes?: string[]; kind?: string }[]; currency: string; onDrill?: (label: string, codes: string[]) => void }) { return <div className="financial-statement"><div className="statement-title"><h3>{title}</h3></div>{rows.map((row) => <div className={`financial-row ${row.kind ?? ""}`} key={row.label}><button disabled={!row.codes?.length || !onDrill} onClick={() => onDrill?.(row.label, row.codes ?? [])}>{row.label}</button><strong>{formatMoney(row.amount, currency)}</strong>{row.previous !== undefined && <><span>{formatMoney(row.previous, currency)}</span><em>{row.previous ? `${((row.amount - row.previous) / Math.abs(row.previous) * 100).toFixed(1)}%` : "—"}</em></>}</div>)}</div>; }
function StatementSection({ title, lines, currency, onDrill }: { title: string; lines: { label: string; amount: number; accountCodes: string[] }[]; currency: string; onDrill: (label: string, codes: string[]) => void }) { return <section className="statement-section"><h4>{title}</h4>{lines.filter((line) => line.amount || !line.label.includes("الأصول")).map((line) => <div key={line.label}><button onClick={() => onDrill(line.label, line.accountCodes)}>{line.label}</button><strong>{formatMoney(line.amount, currency)}</strong></div>)}<footer><span>{title}</span><strong>{formatMoney(lines.reduce((sum, line) => sum + line.amount, 0), currency)}</strong></footer></section>; }
function DrillDown({ open, onClose, data, filters, t }: { open?: { title: string; codes: string[] }; onClose: () => void; data: ErpData; filters: FinancialFilters; t: T }) { if (!open) return null; const rows = accountJournalLines(data, filters, open.codes); return <Modal open title={`${t("تفاصيل", "Details")} — ${open.title}`} onClose={onClose}><div className="dialog-body table-scroll"><table><thead><tr><th>{t("التاريخ", "Date")}</th><th>{t("القيد", "Journal")}</th><th>{t("المستند", "Document")}</th><th>{t("البيان", "Description")}</th><th>{t("مدين", "Debit")}</th><th>{t("دائن", "Credit")}</th></tr></thead><tbody>{rows.map(({ entry, line }, index) => <tr key={`${entry.id}-${index}`}><td>{entry.date}</td><td><strong>{entry.number}</strong></td><td>{entry.sourceNumber}</td><td>{line.description}</td><td>{formatMoney(line.debit, data.settings.currency)}</td><td>{formatMoney(line.credit, data.settings.currency)}</td></tr>)}</tbody></table></div><div className="dialog-foot"><button className="btn btn-secondary" onClick={onClose}>{t("إغلاق", "Close")}</button></div></Modal>; }
function previousPeriod(filters: FinancialFilters): FinancialFilters { if (!filters.from) return filters; const start = new Date(`${filters.from}T00:00:00`), end = new Date(`${filters.to}T00:00:00`); const days = Math.round((end.getTime() - start.getTime()) / 86400000) + 1; const previousEnd = new Date(start); previousEnd.setDate(previousEnd.getDate() - 1); const previousStart = new Date(previousEnd); previousStart.setDate(previousStart.getDate() - days + 1); return { ...filters, from: previousStart.toISOString().slice(0, 10), to: previousEnd.toISOString().slice(0, 10) }; }
function exportRows(report: FinancialReport, data: ErpData, filters: FinancialFilters, t: T): (string | number)[][] { if (report.includes("trial")) return [[t("كود الحساب", "Account code"), t("اسم الحساب", "Account name"), t("افتتاحي مدين", "Opening debit"), t("افتتاحي دائن", "Opening credit"), t("حركة مدين", "Period debit"), t("حركة دائن", "Period credit"), t("ختامي مدين", "Closing debit"), t("ختامي دائن", "Closing credit")], ...detailedTrialBalance(data, filters, report === "adjusted-trial" ? "adjusted" : report === "post-closing-trial" ? "post-closing" : "trial").map((row) => [row.accountCode, row.accountName, row.openingDebit, row.openingCredit, row.periodDebit, row.periodCredit, row.closingDebit, row.closingCredit])]; const income = incomeStatement(data, filters); return [[t("البند", "Item"), t("القيمة", "Amount")], [t("إيرادات المشروعات", "Project revenue"), income.projectRevenue], [t("تكلفة المشروعات", "Project costs"), income.projectCost], [t("صافي الربح", "Net profit"), income.netProfit]]; }
