"use client";

import { useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { Archive, ArrowDown, ArrowUp, Plus } from "lucide-react";
import { DataTable } from "@/components/shared/data-table";
import { Modal } from "@/components/shared/modal";
import type { Contract, CostCode, ErpData, Warehouse, WbsNode } from "@/types/erp";
import { formatMoney, uid } from "@/utils/format";

type Commit = (data: ErpData, message?: string) => void;

export function ContractCenter({ data, companyId, commit }: { data: ErpData; companyId: string; commit: Commit }) {
  const [open, setOpen] = useState(false); const contracts = data.contracts.filter((item) => item.companyId === companyId);
  const columns: ColumnDef<Contract>[] = [{ accessorKey: "number", header: "Contract Number", cell: (cell) => <strong>{cell.getValue<string>()}</strong> }, { id: "project", header: "Project Code — Name", cell: (cell) => entityLabel(data.projects, cell.row.original.projectId) }, { id: "customer", header: "Customer", cell: (cell) => entityLabel(data.customers, cell.row.original.customerId) }, { accessorKey: "type", header: "Type" }, { accessorKey: "originalValue", header: "Original Value", cell: (cell) => formatMoney(cell.getValue<number>(), data.settings.currency) }, { id: "variations", header: "Approved Variations", cell: (cell) => formatMoney(data.variationOrders.filter((item) => item.contractId === cell.row.original.id && item.status === "approved").reduce((sum, item) => sum + item.revenueImpact, 0), data.settings.currency) }, { id: "revised", header: "Revised Contract", cell: (cell) => formatMoney(cell.row.original.originalValue + data.variationOrders.filter((item) => item.contractId === cell.row.original.id && item.status === "approved").reduce((sum, item) => sum + item.revenueImpact, 0), data.settings.currency) }, { accessorKey: "retentionRate", header: "Retention %" }, { accessorKey: "status", header: "Status", cell: (cell) => <span className={`badge ${cell.getValue<string>()}`}>{cell.getValue<string>()}</span> }];
  return <><div className="section-command"><div><h3>Contract Master</h3><p>Original Contract + Approved Variations = Revised Contract.</p></div><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={15}/>New Contract</button></div><DataTable data={contracts} columns={columns}/><ContractForm open={open} onClose={() => setOpen(false)} data={data} companyId={companyId} commit={commit}/></>;
}

function ContractForm({ open, onClose, data, companyId, commit }: { open: boolean; onClose: () => void; data: ErpData; companyId: string; commit: Commit }) {
  const projects = data.projects.filter((item) => item.companyId === companyId); const customers = data.customers.filter((item) => item.companyId === companyId); const [number, setNumber] = useState(""); const [projectId, setProjectId] = useState(projects[0]?.id ?? ""); const [customerId, setCustomerId] = useState(customers[0]?.id ?? ""); const [type, setType] = useState<Contract["type"]>("lump-sum"); const [value, setValue] = useState(0); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [advance, setAdvance] = useState(0); const [retention, setRetention] = useState(5); const [terms, setTerms] = useState("30 days"); const [penalty, setPenalty] = useState(0);
  if (!open) return null; const save = () => { if (!number || !projectId || !customerId || value <= 0) return; const timestamp = new Date().toISOString(); const contract: Contract = { id: uid("contract"), createdAt: timestamp, updatedAt: timestamp, number, companyId, projectId, customerId, type, originalValue: value, startDate, endDate, advanceRate: advance, retentionRate: retention, paymentTerms: terms, penaltyRate: penalty, status: "active" }; commit({ ...data, contracts: [...data.contracts, contract] }, "تم إنشاء العقد"); onClose(); };
  return <Modal open title="Create Contract" onClose={onClose}><div className="dialog-body form-grid"><Field label="Contract Number"><input className="input" value={number} onChange={(event) => setNumber(event.target.value)}/></Field><Field label="Project"><select className="input" value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></Field><Field label="Customer"><select className="input" value={customerId} onChange={(event) => setCustomerId(event.target.value)}>{customers.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></Field><Field label="Contract Type"><select className="input" value={type} onChange={(event) => setType(event.target.value as Contract["type"])}><option value="lump-sum">Lump Sum</option><option value="unit-price">Unit Price</option><option value="cost-plus">Cost Plus</option><option value="time-material">Time & Material</option><option value="other">Other</option></select></Field><Field label="Original Value"><input className="input" type="number" value={value || ""} onChange={(event) => setValue(Number(event.target.value))}/></Field><Field label="Start Date"><input className="input" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)}/></Field><Field label="End Date"><input className="input" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)}/></Field><Field label="Advance %"><input className="input" type="number" value={advance} onChange={(event) => setAdvance(Number(event.target.value))}/></Field><Field label="Retention %"><input className="input" type="number" value={retention} onChange={(event) => setRetention(Number(event.target.value))}/></Field><Field label="Penalty %"><input className="input" type="number" value={penalty} onChange={(event) => setPenalty(Number(event.target.value))}/></Field><Field label="Payment Terms"><input className="input" value={terms} onChange={(event) => setTerms(event.target.value)}/></Field></div><Foot onClose={onClose} onSave={save}/></Modal>;
}

export function StructureCenter({ data, companyId, projects, commit }: { data: ErpData; companyId: string; projects: ErpData["projects"]; commit: Commit }) {
  const [tab, setTab] = useState<"wbs" | "cost">("wbs"); const [projectId, setProjectId] = useState(projects[0]?.id ?? ""); const [open, setOpen] = useState(false); const nodes = tab === "wbs" ? data.wbsNodes.filter((item) => item.companyId === companyId && item.projectId === projectId) : data.costCodes.filter((item) => item.companyId === companyId);
  const move = (id: string, delta: number) => { if (tab === "wbs") commit({ ...data, wbsNodes: data.wbsNodes.map((item) => item.id === id ? { ...item, order: Math.max(0, item.order + delta), updatedAt: new Date().toISOString() } : item) }, "تم إعادة ترتيب WBS"); else commit({ ...data, costCodes: data.costCodes.map((item) => item.id === id ? { ...item, order: Math.max(0, item.order + delta), updatedAt: new Date().toISOString() } : item) }, "تم إعادة ترتيب Cost Codes"); };
  const archive = (id: string) => { if (tab === "wbs") commit({ ...data, wbsNodes: data.wbsNodes.map((item) => item.id === id ? { ...item, status: item.status === "active" ? "archived" : "active", updatedAt: new Date().toISOString() } : item) }); else commit({ ...data, costCodes: data.costCodes.map((item) => item.id === id ? { ...item, status: item.status === "active" ? "archived" : "active", updatedAt: new Date().toISOString() } : item) }); };
  const rows = [...nodes].sort((a, b) => a.order - b.order || a.code.localeCompare(b.code)); const columns: ColumnDef<WbsNode | CostCode>[] = [{ accessorKey: "code", header: "Code", cell: (cell) => <strong>{cell.getValue<string>()}</strong> }, { accessorKey: "name", header: "Code — Name", cell: (cell) => `${cell.row.original.code} — ${cell.getValue<string>()}` }, { id: "parent", header: "Parent", cell: (cell) => { const parent = nodes.find((item) => item.id === cell.row.original.parentId); return parent ? `${parent.code} — ${parent.name}` : "Root"; } }, { accessorKey: "status", header: "Status", cell: (cell) => <span className={`badge ${cell.getValue<string>()}`}>{cell.getValue<string>()}</span> }, { id: "actions", header: "Reorder / Archive", cell: (cell) => <div className="row-actions"><button onClick={() => move(cell.row.original.id, -1)}><ArrowUp size={14}/></button><button onClick={() => move(cell.row.original.id, 1)}><ArrowDown size={14}/></button><button onClick={() => archive(cell.row.original.id)}><Archive size={14}/></button></div> }];
  return <><div className="section-command"><div><h3>WBS & Cost Code Trees</h3><p>Hierarchical CRUD with parent, reorder and archive.</p></div><div className="actions"><button className={`btn ${tab === "wbs" ? "btn-primary" : "btn-secondary"}`} onClick={() => setTab("wbs")}>WBS Tree</button><button className={`btn ${tab === "cost" ? "btn-primary" : "btn-secondary"}`} onClick={() => setTab("cost")}>Cost Code Tree</button>{tab === "wbs" && <select className="select" value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select>}<button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={15}/>Add Node</button></div></div><TreePreview nodes={rows}/><DataTable data={rows} columns={columns}/><TreeNodeForm open={open} onClose={() => setOpen(false)} data={data} companyId={companyId} projectId={projectId} type={tab} nodes={nodes} commit={commit}/></>;
}

function TreePreview({ nodes }: { nodes: Array<WbsNode | CostCode> }) { const roots = nodes.filter((item) => !item.parentId); const render = (node: WbsNode | CostCode, level: number): React.ReactNode => <div key={node.id}><div className="tree-node" style={{ paddingInlineStart: 14 + level * 24 }}><i/>{node.code} — {node.name}</div>{nodes.filter((item) => item.parentId === node.id).map((child) => render(child, level + 1))}</div>; return <div className="tree-preview">{roots.map((item) => render(item, 0))}</div>; }
function TreeNodeForm({ open, onClose, data, companyId, projectId, type, nodes, commit }: { open: boolean; onClose: () => void; data: ErpData; companyId: string; projectId: string; type: "wbs" | "cost"; nodes: Array<WbsNode | CostCode>; commit: Commit }) { const [code, setCode] = useState(""); const [name, setName] = useState(""); const [parentId, setParent] = useState(""); if (!open) return null; const save = () => { if (!code || !name) return; const timestamp = new Date().toISOString(); if (type === "wbs") { const node: WbsNode = { id: uid("wbs"), createdAt: timestamp, updatedAt: timestamp, companyId, projectId, code, name, parentId: parentId || undefined, order: nodes.length + 1, status: "active" }; commit({ ...data, wbsNodes: [...data.wbsNodes, node] }, "تم إضافة WBS Node"); } else { const node: CostCode = { id: uid("cost"), createdAt: timestamp, updatedAt: timestamp, companyId, code, name, parentId: parentId || undefined, order: nodes.length + 1, status: "active" }; commit({ ...data, costCodes: [...data.costCodes, node] }, "تم إضافة Cost Code"); } onClose(); }; return <Modal open title={type === "wbs" ? "Add WBS Node" : "Add Cost Code"} onClose={onClose}><div className="dialog-body form-grid"><Field label="Code"><input className="input" value={code} onChange={(event) => setCode(event.target.value)}/></Field><Field label="Name"><input className="input" value={name} onChange={(event) => setName(event.target.value)}/></Field><Field label="Parent"><select className="input" value={parentId} onChange={(event) => setParent(event.target.value)}><option value="">Root</option>{nodes.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></Field></div><Foot onClose={onClose} onSave={save}/></Modal>; }

export function WarehouseCenter({ data, companyId, projects, commit }: { data: ErpData; companyId: string; projects: ErpData["projects"]; commit: Commit }) { const [open, setOpen] = useState(false); const warehouses = data.warehouses.filter((item) => item.companyId === companyId); const stock = (warehouse: Warehouse) => data.inventoryMovements.filter((item) => item.warehouse === warehouse.name || item.warehouse === warehouse.code).reduce((sum, item) => sum + (["receipt", "return"].includes(item.type) ? item.quantity : item.type === "issue" ? -item.quantity : 0), 0); const columns: ColumnDef<Warehouse>[] = [{ accessorKey: "code", header: "Warehouse Code", cell: (cell) => <strong>{cell.getValue<string>()}</strong> }, { accessorKey: "name", header: "Code — Name", cell: (cell) => `${cell.row.original.code} — ${cell.getValue<string>()}` }, { accessorKey: "type", header: "Type" }, { id: "project", header: "Project", cell: (cell) => entityLabel(data.projects, cell.row.original.projectId) }, { accessorKey: "location", header: "Location" }, { accessorKey: "keeper", header: "Keeper" }, { id: "physical", header: "Physical Stock", cell: (cell) => stock(cell.row.original) }, { accessorKey: "reservedStock", header: "Reserved Stock" }, { id: "available", header: "Available Stock", cell: (cell) => stock(cell.row.original) - cell.row.original.reservedStock }, { accessorKey: "status", header: "Status", cell: (cell) => <span className={`badge ${cell.getValue<string>()}`}>{cell.getValue<string>()}</span> }]; return <><div className="section-command"><div><h3>Warehouse Master</h3><p>Company and project warehouses with Physical, Reserved and Available stock.</p></div><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={15}/>New Warehouse</button></div><div className="segment-tabs project-tabs">{["Overview", "Stock", "Receipts", "Issues", "Transfers", "Returns", "Adjustments", "Reservations", "Documents"].map((item, index) => <button className={index === 0 ? "active" : ""} key={item}>{item}</button>)}</div><DataTable data={warehouses} columns={columns}/><WarehouseForm open={open} onClose={() => setOpen(false)} data={data} companyId={companyId} projects={projects} commit={commit}/></>; }
function WarehouseForm({ open, onClose, data, companyId, projects, commit }: { open: boolean; onClose: () => void; data: ErpData; companyId: string; projects: ErpData["projects"]; commit: Commit }) { const [code, setCode] = useState(""); const [name, setName] = useState(""); const [type, setType] = useState<Warehouse["type"]>("project"); const [projectId, setProject] = useState(""); const [location, setLocation] = useState(""); const [keeper, setKeeper] = useState(""); if (!open) return null; const save = () => { if (!code || !name) return; const timestamp = new Date().toISOString(); const warehouse: Warehouse = { id: uid("wh"), createdAt: timestamp, updatedAt: timestamp, companyId, projectId: projectId || undefined, code, name, type, location, keeper, reservedStock: 0, status: "active" }; commit({ ...data, warehouses: [...data.warehouses, warehouse] }, "تم إنشاء المخزن"); onClose(); }; return <Modal open title="Create Warehouse" onClose={onClose}><div className="dialog-body form-grid"><Field label="Code"><input className="input" value={code} onChange={(event) => setCode(event.target.value)}/></Field><Field label="Name"><input className="input" value={name} onChange={(event) => setName(event.target.value)}/></Field><Field label="Type"><select className="input" value={type} onChange={(event) => setType(event.target.value as Warehouse["type"])}><option value="company-main">Company Main Warehouse</option><option value="project">Project Warehouse</option><option value="site">Site Warehouse</option><option value="temporary">Temporary Warehouse</option><option value="equipment">Equipment Warehouse</option></select></Field><Field label="Project (optional)"><select className="input" value={projectId} onChange={(event) => setProject(event.target.value)}><option value="">Company Level</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></Field><Field label="Location"><input className="input" value={location} onChange={(event) => setLocation(event.target.value)}/></Field><Field label="Keeper"><input className="input" value={keeper} onChange={(event) => setKeeper(event.target.value)}/></Field></div><Foot onClose={onClose} onSave={save}/></Modal>; }

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="field"><label>{label}</label>{children}</div>; }
function Foot({ onClose, onSave }: { onClose: () => void; onSave: () => void }) { return <div className="dialog-foot"><button className="btn btn-secondary" onClick={onClose}>إلغاء</button><button className="btn btn-primary" onClick={onSave}>حفظ</button></div>; }
function entityLabel<T extends { id: string; code?: string; name: string }>(items: T[], id?: string) { const item = items.find((entry) => entry.id === id); return item ? `${item.code ? `${item.code} — ` : ""}${item.name}` : "—"; }
