"use client";
import { useState } from "react";
import { Modal } from "@/components/shared/modal";
import type { ErpData } from "@/types/erp";

export type QuickMode = "boq"|"po"|"inventory"|"expense"|"certificate"|"journal"|"document";
const titles:Record<QuickMode,string>={boq:"إضافة بند مقايسة",po:"إنشاء أمر شراء",inventory:"تسجيل حركة مخزون",expense:"تسجيل مصروف مشروع",certificate:"إنشاء مستخلص",journal:"إضافة قيد يومية",document:"إضافة بيانات مستند"};

export function QuickEntryForm({mode,data,onClose,onSave}:{mode:QuickMode|null;data:ErpData;onClose:()=>void;onSave:(mode:QuickMode,values:Record<string,string>)=>void}){
 const [values,setValues]=useState<Record<string,string>>({}); if(!mode)return null;
 const set=(name:string,value:string)=>setValues(old=>({...old,[name]:value}));
 const submit=(event:React.FormEvent)=>{event.preventDefault();onSave(mode,values);};
 return <Modal title={titles[mode]} open onClose={onClose}><form onSubmit={submit}><div className="dialog-body form-grid">
  {mode!=="journal"&&mode!=="document"&&<Select label="المشروع" name="projectId" required values={values} set={set} options={data.projects.filter(p=>p.status==="active").map(p=>({value:p.id,label:p.name}))}/>} 
  {mode==="boq"&&<><Input label="كود البند" name="code" required values={values} set={set}/><Input label="الوصف" name="description" required values={values} set={set}/><Input label="الوحدة" name="unit" required values={values} set={set}/><Input label="الكمية" name="quantity" type="number" required values={values} set={set}/><Input label="سعر البيع" name="unitRate" type="number" required values={values} set={set}/><Input label="سعر الميزانية" name="budgetRate" type="number" required values={values} set={set}/></>}
  {mode==="po"&&<><Select label="المورد" name="supplierId" required values={values} set={set} options={data.suppliers.filter(p=>p.status==="active").map(p=>({value:p.id,label:p.name}))}/><Input label="الوصف" name="description" required values={values} set={set}/><Input label="القيمة" name="amount" type="number" required values={values} set={set}/></>}
  {mode==="inventory"&&<><Input label="المادة" name="material" required values={values} set={set}/><Input label="المخزن" name="warehouse" required values={values} set={set}/><Select label="نوع الحركة" name="type" required values={values} set={set} options={[{value:"receipt",label:"استلام"},{value:"issue",label:"صرف"},{value:"return",label:"مرتجع"},{value:"transfer",label:"تحويل"}]}/><Input label="الكمية" name="quantity" type="number" required values={values} set={set}/><Input label="تكلفة الوحدة" name="unitCost" type="number" required values={values} set={set}/><Input label="Cost Code — Name" name="costCode" required values={values} set={set}/><Select label="BOQ Item" name="boqItemId" values={values} set={set} options={data.boqItems.filter(item=>!values.projectId||item.projectId===values.projectId).map(item=>({value:item.id,label:`${item.code} — ${item.description}`}))}/></>}
  {mode==="expense"&&<><Input label="كود التكلفة" name="costCode" required values={values} set={set}/><Input label="البيان" name="description" required values={values} set={set}/><Input label="القيمة" name="amount" type="number" required values={values} set={set}/><Input label="التاريخ" name="date" type="date" required values={values} set={set}/></>}
  {mode==="certificate"&&<><Select label="نوع المستخلص" name="type" required values={values} set={set} options={[{value:"customer",label:"مستخلص عميل"},{value:"subcontractor",label:"مستخلص مقاول باطن"}]}/><Select label="الطرف" name="partyId" required values={values} set={set} options={[...data.customers,...data.subcontractors].filter(p=>p.status==="active").map(p=>({value:p.id,label:p.name}))}/><Input label="إجمالي الأعمال" name="grossAmount" type="number" required values={values} set={set}/><Input label="نسبة الاحتجاز %" name="retentionRate" type="number" required values={values} set={set}/><Input label="الضريبة %" name="taxRate" type="number" required values={values} set={set}/></>}
  {mode==="journal"&&<><Input label="البيان" name="description" required values={values} set={set}/><Input label="التاريخ" name="date" type="date" required values={values} set={set}/><Select label="الحساب المدين" name="debitAccount" required values={values} set={set} options={data.chartOfAccounts.filter(account=>account.active).map(account=>({value:account.code,label:`${account.code} — ${account.name}`}))}/><Select label="الحساب الدائن" name="creditAccount" required values={values} set={set} options={data.chartOfAccounts.filter(account=>account.active).map(account=>({value:account.code,label:`${account.code} — ${account.name}`}))}/><Input label="القيمة" name="amount" type="number" required values={values} set={set}/><Select label="المشروع (اختياري)" name="projectId" values={values} set={set} options={[{value:"",label:"Company Level"},...data.projects.map(p=>({value:p.id,label:`${p.code} — ${p.name}`}))]}/><Input label="Cost Code — Name" name="costCode" values={values} set={set}/><Input label="Reference" name="reference" values={values} set={set}/></>}
  {mode==="document"&&<><Input label="اسم الملف" name="fileName" required values={values} set={set}/><Select label="التصنيف" name="category" required values={values} set={set} options={["Contract","BOQ","Drawing","Invoice","Certificate","PO","Site Report","Photo","Other"].map(x=>({value:x,label:x}))}/><Select label="المشروع" name="projectId" values={values} set={set} options={[{value:"",label:"عام"},...data.projects.map(p=>({value:p.id,label:p.name}))]}/><Input label="الحجم بالكيلوبايت" name="size" type="number" required values={values} set={set}/><Input label="الوصف" name="description" required values={values} set={set}/></>}
 </div><div className="dialog-foot"><button type="button" className="btn btn-secondary" onClick={onClose}>إلغاء</button><button className="btn btn-primary" type="submit">حفظ واعتماد</button></div></form></Modal>
}
function Input({label,name,values,set,type="text",required=false}:{label:string;name:string;values:Record<string,string>;set:(n:string,v:string)=>void;type?:string;required?:boolean}){return <div className="field"><label>{label}</label><input className="input" type={type} required={required} min={type==="number"?0:undefined} value={values[name]??""} onChange={e=>set(name,e.target.value)}/></div>}
function Select({label,name,values,set,options,required=false}:{label:string;name:string;values:Record<string,string>;set:(n:string,v:string)=>void;options:{value:string;label:string}[];required?:boolean}){return <div className="field"><label>{label}</label><select className="input" required={required} value={values[name]??""} onChange={e=>set(name,e.target.value)}><option value="">اختر...</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}
