"use client";

import { useMemo, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { AlertTriangle, CheckCircle2, FileCheck2, Plus, Search, TrendingUp, WalletCards } from "lucide-react";
import { DataTable } from "@/components/shared/data-table";
import { Modal } from "@/components/shared/modal";
import { buildCertificate, certificateHistory, certificateNet, projectCertificateSummary } from "@/services/certificate-engine";
import { registerOperationalDocument } from "@/services/accounting-core";
import { useUiStore } from "@/store/ui-store";
import type { Certificate, CertificateMethod, ErpData, Project } from "@/types/erp";
import { formatMoney } from "@/utils/format";

type Commit = (data: ErpData, message?: string) => void;
type T = (ar: string, en: string) => string;

export function ProgressCertificateCenter({ data, projects, commit }: { data: ErpData; projects: Project[]; commit: Commit }) {
  const language = useUiStore((state) => state.language); const t: T = (ar, en) => language === "ar" ? ar : en;
  const [projectId, setProjectId] = useState(projects[0]?.id ?? ""); const [projectSearch, setProjectSearch] = useState(""); const [type, setType] = useState<Certificate["type"]>("customer"); const [status, setStatus] = useState("all"); const [open, setOpen] = useState(false);
  const visibleProjects = projects.filter((item) => `${item.code} ${item.name}`.toLowerCase().includes(projectSearch.toLowerCase())); const project = projects.find((item) => item.id === projectId) ?? projects[0];
  if (!project) return <div className="empty"><strong>{t("لا توجد مشروعات داخل الشركة الحالية", "No projects in the current company")}</strong></div>;
  const summary = projectCertificateSummary(project.id, type, data); const history = certificateHistory(project.id, type, data).filter((item) => status === "all" || item.status === status);
  const totalContracts = projects.reduce((sum, item) => sum + projectCertificateSummary(item.id, type, data).revisedContract, 0); const totalApproved = projects.reduce((sum, item) => sum + projectCertificateSummary(item.id, type, data).certifiedValue, 0); const totalCollected = projects.reduce((sum, item) => sum + projectCertificateSummary(item.id, type, data).collected, 0); const totalRetention = data.certificates.filter((item) => projects.some((project) => project.id === item.projectId) && item.type === type).reduce((sum, item) => sum + certificateNet(item).retention, 0);
  const columns: ColumnDef<Certificate>[] = [
    { accessorKey: "number", header: t("المستخلص", "Certificate"), cell: (cell) => <strong>{cell.getValue<string>()}</strong> }, { accessorKey: "period", header: t("الفترة", "Period") },
    { accessorKey: "previousProgress", header: t("السابق %", "Previous %"), cell: (cell) => `${Number(cell.getValue() ?? 0).toFixed(1)}%` }, { accessorKey: "currentPeriodProgress", header: t("الحالي %", "Current %"), cell: (cell) => `${Number(cell.getValue() ?? 0).toFixed(1)}%` }, { accessorKey: "cumulativeProgress", header: t("التراكمي %", "Cumulative %"), cell: (cell) => <strong>{Number(cell.getValue() ?? 0).toFixed(1)}%</strong> },
    { accessorKey: "grossAmount", header: t("قيمة الأعمال الحالية", "Current work value"), cell: (cell) => formatMoney(cell.getValue<number>(), data.settings.currency) }, { id: "retention", header: t("الاحتجاز", "Retention"), cell: (cell) => formatMoney(certificateNet(cell.row.original).retention, data.settings.currency) }, { id: "net", header: t("الصافي", "Net"), cell: (cell) => formatMoney(certificateNet(cell.row.original).net, data.settings.currency) }, { accessorKey: "paidAmount", header: t("المحصل", "Collected"), cell: (cell) => formatMoney(cell.getValue<number>(), data.settings.currency) }, { id: "outstanding", header: t("المتبقي", "Outstanding"), cell: (cell) => formatMoney(Math.max(0, certificateNet(cell.row.original).net - cell.row.original.paidAmount), data.settings.currency) }, { accessorKey: "status", header: t("الحالة", "Status"), cell: (cell) => <span className={`badge ${cell.getValue<string>()}`}>{cell.getValue<string>()}{cell.row.original.isFinal ? ` · ${t("ختامي", "FINAL")}` : ""}</span> },
  ];
  return <div className="certificate-center"><div className="report-command"><div><span>{t("إدارة دورة المستخلص", "CERTIFICATE WORKFLOW")}</span><h3>{t("المستخلصات", "Certificates")}</h3><p>{t("إدارة مستخلصات العملاء ومقاولي الباطن ومتابعة نسب التنفيذ والتحصيل", "Manage customer and subcontractor certificates, progress and collection")}</p></div><button className="btn btn-primary" disabled={Boolean(summary.latest?.isFinal)} onClick={() => setOpen(true)}><Plus size={15}/>{t("إنشاء مستخلص", "Create Certificate")}</button></div>
    <div className="metrics certificate-metrics"><CertificateMetric label={t("إجمالي قيمة العقود", "Total contracts")} value={formatMoney(totalContracts, data.settings.currency)} note={t("بعد التغييرات المعتمدة", "After approved variations")} icon={TrendingUp}/><CertificateMetric label={t("إجمالي المعتمد", "Total certified")} value={formatMoney(totalApproved, data.settings.currency)} note={`${summary.certifiedProgress.toFixed(1)}%`} icon={FileCheck2}/><CertificateMetric label={t("إجمالي المحصل", "Total collected")} value={formatMoney(totalCollected, data.settings.currency)} note={`${summary.collectedProgress.toFixed(1)}%`} icon={WalletCards}/><CertificateMetric label={t("المتبقي", "Outstanding")} value={formatMoney(Math.max(0, totalApproved - totalCollected), data.settings.currency)} note={t("قبل التحصيلات اللاحقة", "Before future collections")} icon={AlertTriangle}/><CertificateMetric label={t("الاحتجازات", "Retentions")} value={formatMoney(totalRetention, data.settings.currency)} note={t("تراكمي", "Cumulative")} icon={WalletCards}/></div>
    <div className="certificate-filters"><label><Search size={15}/><input className="input" placeholder={t("ابحث في المشروعات...", "Search projects...")} value={projectSearch} onChange={(event) => setProjectSearch(event.target.value)}/></label><select className="input" value={project.id} onChange={(event) => setProjectId(event.target.value)} title={`${project.code} — ${project.name}`}>{visibleProjects.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select><select className="input" value={type} onChange={(event) => setType(event.target.value as Certificate["type"])}><option value="customer">{t("مستخلصات العملاء", "Customer Certificates")}</option><option value="subcontractor">{t("مستخلصات مقاولي الباطن", "Subcontractor Certificates")}</option></select><select className="input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">{t("كل الحالات", "All statuses")}</option><option value="submitted">{t("مرسل", "Submitted")}</option><option value="approved">{t("معتمد", "Approved")}</option><option value="posted">{t("مرحّل", "Posted")}</option></select></div>
    <div className="certificate-contract-summary"><div><span>{t("العقد الأصلي", "Original contract")}</span><strong>{formatMoney(summary.originalContract, data.settings.currency)}</strong></div><div><span>{t("التغييرات المعتمدة", "Approved variations")}</span><strong>{formatMoney(summary.approvedVariations, data.settings.currency)}</strong></div><div><span>{t("قيمة العقد المعدلة المستخدمة", "Revised contract value used")}</span><strong>{formatMoney(summary.revisedContract, data.settings.currency)}</strong></div><div><span>{t("المتبقي من العقد", "Remaining contract")}</span><strong>{formatMoney(summary.remainingContractValue, data.settings.currency)}</strong></div></div>
    <CertificateTimeline history={history} currency={data.settings.currency} t={t}/><DataTable data={history} columns={columns}/><CertificateWizard open={open} onClose={() => setOpen(false)} data={data} project={project} type={type} commit={commit} t={t}/>
  </div>;
}

function CertificateWizard({ open, onClose, data, project, type, commit, t }: { open: boolean; onClose: () => void; data: ErpData; project: Project; type: Certificate["type"]; commit: Commit; t: T }) {
  const summary = projectCertificateSummary(project.id, type, data); const [step, setStep] = useState(0); const [method, setMethod] = useState<CertificateMethod>("overall-progress"); const [cumulative, setCumulative] = useState(summary.certifiedProgress); const [partyId, setPartyId] = useState(type === "customer" ? project.customerId : data.subcontractors.find((item) => item.companyId === project.companyId)?.id ?? ""); const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7)); const [retentionRate, setRetentionRate] = useState(data.contracts.find((item) => item.projectId === project.id)?.retentionRate ?? 5); const [taxRate, setTaxRate] = useState(data.settings.vatRate); const [advanceRecovery, setAdvanceRecovery] = useState(0); const [withholding, setWithholding] = useState(0); const [materialDeductions, setMaterialDeductions] = useState(0); const [equipmentDeductions, setEquipmentDeductions] = useState(0); const [penalty, setPenalty] = useState(0); const [other, setOther] = useState(0); const [isFinal, setFinal] = useState(false); const [quantities, setQuantities] = useState<Record<string, number>>({});
  const preview = useMemo(() => { try { return buildCertificate({ projectId: project.id, partyId, type, method, period, cumulativeProgress: cumulative, currentQuantities: quantities, retentionRate, taxRate, currentAdvanceRecovery: advanceRecovery, withholdingAmount: withholding, materialDeductions, equipmentDeductions, penaltyAmount: penalty, otherDeductions: other, isFinal }, data); } catch { return undefined; } }, [project.id, partyId, type, method, period, cumulative, quantities, retentionRate, taxRate, advanceRecovery, withholding, materialDeductions, equipmentDeductions, penalty, other, isFinal, data]);
  if (!open) return null; const parties = type === "customer" ? data.customers.filter((item) => item.companyId === project.companyId) : data.subcontractors.filter((item) => item.companyId === project.companyId); const boqItems = data.boqItems.filter((item) => item.projectId === project.id); const currentProgress = cumulative - summary.certifiedProgress; const previousValue = summary.revisedContract * summary.certifiedProgress / 100; const currentValue = summary.revisedContract * currentProgress / 100; const cumulativeValue = summary.revisedContract * cumulative / 100;
  const save = () => { if (!preview) return; try { const totals = certificateNet(preview); const document = registerOperationalDocument({ type: type === "customer" ? "customer-certificate" : "subcontractor-certificate", sourceNumber: preview.number, companyId: project.companyId, projectId: project.id, partyId, taxableAmount: preview.grossAmount, taxAmount: totals.tax, deductions: totals.deductions, date: `${period}-01`, description: `${type === "customer" ? "مستخلص عميل" : "مستخلص مقاول باطن"} ${preview.number}` }, data); commit({ ...data, certificates: [...data.certificates, preview], accountingDocuments: [...data.accountingDocuments, document] }, `${t("تم إنشاء", "Created")} ${preview.number}`); onClose(); } catch (error) { window.alert(error instanceof Error ? error.message : t("تعذر إنشاء المستخلص", "Could not create certificate")); } };
  const steps = [t("بيانات المستخلص", "Certificate data"), t("نسبة الإنجاز / الكميات", "Progress / quantities"), t("السابق والحالي", "Previous and current"), t("الخصومات والضرائب", "Deductions and taxes"), t("مراجعة", "Review"), t("حفظ", "Save")];
  return <Modal open title={t("معالج إنشاء المستخلص", "Certificate Wizard")} onClose={onClose} className="certificate-wizard"><div className="wizard-steps">{steps.map((label, index) => <div className={index <= step ? "active" : ""} key={label}><i>{index < step ? <CheckCircle2 size={14}/> : index + 1}</i><span>{label}</span></div>)}</div><div className="dialog-body wizard-body">
    {step === 0 && <div className="form-grid"><FormField label={t("نوع المستخلص", "Certificate type")}><input className="input" value={type === "customer" ? t("مستخلص عميل", "Customer certificate") : t("مستخلص مقاول باطن", "Subcontractor certificate")} disabled/></FormField><FormField label={t("الطرف", "Party")}><select className="input" value={partyId} onChange={(event) => setPartyId(event.target.value)}>{parties.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></FormField><FormField label={t("الفترة", "Period")}><input className="input" type="month" value={period} onChange={(event) => setPeriod(event.target.value)}/></FormField><FormField label={t("طريقة القياس", "Measurement method")}><select className="input" value={method} onChange={(event) => setMethod(event.target.value as CertificateMethod)}><option value="overall-progress">{t("نسبة الإنجاز التراكمية", "Overall cumulative progress")}</option><option value="boq-quantities">{t("كميات بنود المقايسة المنفذة", "Executed BOQ quantities")}</option></select></FormField></div>}
    {step === 1 && (method === "overall-progress" ? <div><FormField label={t("نسبة الإنجاز التراكمية الجديدة", "New cumulative progress %")}><input className="input progress-input" type="number" min={summary.certifiedProgress} max={100} value={cumulative} onChange={(event) => setCumulative(Number(event.target.value))}/></FormField><LiveProgress previous={summary.certifiedProgress} cumulative={cumulative} contractValue={summary.revisedContract} currency={data.settings.currency} t={t}/></div> : <div className="boq-certificate-lines">{boqItems.map((boq) => { const previous = certificateHistory(project.id, type, data).flatMap((item) => item.lines ?? []).filter((item) => item.boqItemId === boq.id).at(-1)?.cumulativeQuantity ?? 0; return <div key={boq.id}><strong>{boq.code} — {boq.description}</strong><span>{t("العقد", "Contract")}: {boq.quantity}</span><span>{t("السابق", "Previous")}: {previous}</span><input className="input" type="number" min={0} max={boq.quantity - previous} value={quantities[boq.id] || ""} onChange={(event) => setQuantities({ ...quantities, [boq.id]: Number(event.target.value) })}/><span>{t("المتبقي", "Remaining")}: {boq.quantity - previous - (quantities[boq.id] || 0)}</span></div>; })}</div>)}
    {step === 2 && <div className="certificate-value-grid"><Value label={t("نسبة الإنجاز السابقة", "Previous progress")} value={`${summary.certifiedProgress.toFixed(2)}%`}/><Value label={t("النسبة الحالية للمستخلص", "Current certificate progress")} value={`${currentProgress.toFixed(2)}%`}/><Value label={t("النسبة التراكمية", "Cumulative progress")} value={`${cumulative.toFixed(2)}%`}/><Value label={t("قيمة الأعمال السابقة", "Previous work value")} value={formatMoney(previousValue, data.settings.currency)}/><Value label={t("قيمة الأعمال الحالية", "Current work value")} value={formatMoney(currentValue, data.settings.currency)}/><Value label={t("القيمة التراكمية", "Cumulative value")} value={formatMoney(cumulativeValue, data.settings.currency)}/><Value label={t("المتبقي", "Remaining")} value={formatMoney(summary.revisedContract - cumulativeValue, data.settings.currency)}/></div>}
    {step === 3 && <div className="form-grid"><FormField label={t("الاحتجاز %", "Retention %")}><input className="input" type="number" value={retentionRate} onChange={(event) => setRetentionRate(Number(event.target.value))}/></FormField><FormField label={t("ضريبة القيمة المضافة %", "VAT %")}><input className="input" type="number" value={taxRate} onChange={(event) => setTaxRate(Number(event.target.value))}/></FormField><Money label={t("استرداد الدفعة المقدمة", "Advance recovery")} value={advanceRecovery} set={setAdvanceRecovery}/><Money label={t("الخصم من المنبع", "Withholding")} value={withholding} set={setWithholding}/><Money label={t("خصم مواد", "Material deduction")} value={materialDeductions} set={setMaterialDeductions}/><Money label={t("خصم معدات", "Equipment deduction")} value={equipmentDeductions} set={setEquipmentDeductions}/><Money label={t("غرامات", "Penalties")} value={penalty} set={setPenalty}/><Money label={t("خصومات أخرى", "Other deductions")} value={other} set={setOther}/><label className="final-check"><input type="checkbox" checked={isFinal} onChange={(event) => setFinal(event.target.checked)}/>{t("المستخلص الختامي — يمنع إنشاء مستخلص لاحق", "Final certificate — locks future certificates")}</label></div>}
    {step >= 4 && <div><div className="notice"><CheckCircle2 size={18}/>{t("راجع القيم قبل الحفظ. سيُنشئ النظام مستندًا محاسبيًا مرسلًا للمراجعة دون ترحيل مباشر.", "Review before saving. An accounting document will be submitted without direct posting.")}</div><div className="certificate-value-grid"><Value label={t("العقد المعدل", "Revised contract")} value={formatMoney(summary.revisedContract, data.settings.currency)}/><Value label={t("السابق", "Previous")} value={`${summary.certifiedProgress.toFixed(2)}%`}/><Value label={t("الحالي", "Current")} value={`${preview?.currentPeriodProgress?.toFixed(2) ?? "—"}%`}/><Value label={t("التراكمي", "Cumulative")} value={`${preview?.cumulativeProgress?.toFixed(2) ?? "—"}%`}/><Value label={t("قيمة المستخلص الحالية", "Current certificate value")} value={formatMoney(preview?.grossAmount ?? 0, data.settings.currency)}/><Value label={t("الصافي بعد الضرائب والخصومات", "Net after tax and deductions")} value={formatMoney(preview ? certificateNet(preview).net : 0, data.settings.currency)}/></div></div>}
  </div><div className="dialog-foot wizard-actions"><button className="btn btn-secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>{t("السابق", "Previous")}</button>{step < 5 ? <button className="btn btn-primary" disabled={step === 4 && !preview} onClick={() => setStep(step + 1)}>{t("التالي", "Next")}</button> : <button className="btn btn-primary" disabled={!preview || !partyId} onClick={save}>{t("حفظ وإرسال للمراجعة", "Save and submit")}</button>}</div></Modal>;
}

function LiveProgress({ previous, cumulative, contractValue, currency, t }: { previous: number; cumulative: number; contractValue: number; currency: string; t: T }) { const current = cumulative - previous; return <div className="live-calculation"><Value label={t("السابق", "Previous")} value={`${previous.toFixed(2)}%`}/><Value label={t("الحالي", "Current")} value={`${current.toFixed(2)}%`}/><Value label={t("التراكمي", "Cumulative")} value={`${cumulative.toFixed(2)}%`}/><Value label={t("المتبقي", "Remaining")} value={`${(100 - cumulative).toFixed(2)}%`}/><Value label={t("قيمة الحالي", "Current value")} value={formatMoney(contractValue * current / 100, currency)}/><Value label={t("القيمة التراكمية", "Cumulative value")} value={formatMoney(contractValue * cumulative / 100, currency)}/></div>; }
function CertificateTimeline({ history, currency, t }: { history: Certificate[]; currency: string; t: T }) { if (!history.length) return null; return <div className="certificate-timeline">{history.map((item, index) => <div key={item.id}><i>{index + 1}</i><strong>{item.number}{item.isFinal ? ` · ${t("ختامي", "Final")}` : ""}</strong><span>{t("الحالي", "Current")} {item.currentPeriodProgress?.toFixed(1)}% · {t("التراكمي", "Cumulative")} {item.cumulativeProgress?.toFixed(1)}%</span><small>{formatMoney(certificateNet(item).net, currency)} · {item.paidAmount >= certificateNet(item).net ? t("محصل", "Collected") : t("قيد التحصيل", "Outstanding")}</small></div>)}</div>; }
function CertificateMetric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: React.ElementType }) { return <div className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon size={18}/></span></div><strong>{value}</strong><small>{note}</small></div>; }
function FormField({ label, children }: { label: string; children: React.ReactNode }) { return <div className="field"><label>{label}</label>{children}</div>; }
function Money({ label, value, set }: { label: string; value: number; set: (value: number) => void }) { return <FormField label={label}><input className="input" type="number" value={value || ""} onChange={(event) => set(Number(event.target.value))}/></FormField>; }
function Value({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
