"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { Modal } from "@/components/shared/modal";
import type { Company, Party, Project } from "@/types/erp";

const companySchema = z.object({ name:z.string().min(2,"الاسم مطلوب"),nameEn:z.string().min(2,"English name is required"),taxNumber:z.string().min(3,"الرقم الضريبي مطلوب"),phone:z.string().min(7,"رقم الهاتف غير صحيح"),email:z.email("البريد غير صحيح"),address:z.string().min(3,"العنوان مطلوب") });
export type CompanyInput=z.infer<typeof companySchema>;
export function CompanyForm({open,onClose,onSave,initial}:{open:boolean;onClose:()=>void;onSave:(v:CompanyInput)=>void;initial?:Company}){const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<CompanyInput>({resolver:zodResolver(companySchema),values:initial?{name:initial.name,nameEn:initial.nameEn,taxNumber:initial.taxNumber,phone:initial.phone,email:initial.email,address:initial.address}:undefined,defaultValues:{name:"",nameEn:"",taxNumber:"",phone:"",email:"",address:""}});return <Modal title={initial?"تعديل الشركة":"إضافة شركة جديدة"} open={open} onClose={onClose}><form onSubmit={handleSubmit(onSave)}><div className="dialog-body form-grid"><div className="section-title">المعلومات الأساسية</div><Field label="اسم الشركة بالعربية" error={errors.name?.message}><input className="input" {...register("name")}/></Field><Field label="Company name" error={errors.nameEn?.message}><input className="input" dir="ltr" {...register("nameEn")}/></Field><Field label="الرقم الضريبي" error={errors.taxNumber?.message}><input className="input" dir="ltr" {...register("taxNumber")}/></Field><Field label="رقم الهاتف" error={errors.phone?.message}><input className="input" dir="ltr" {...register("phone")}/></Field><Field label="البريد الإلكتروني" error={errors.email?.message}><input className="input" dir="ltr" {...register("email")}/></Field><Field label="العنوان" error={errors.address?.message}><input className="input" {...register("address")}/></Field></div><FormFoot onClose={onClose} loading={isSubmitting}/></form></Modal>}

const partySchema=z.object({name:z.string().min(2,"الاسم مطلوب"),code:z.string().min(2,"الكود مطلوب"),phone:z.string().min(7,"رقم الهاتف غير صحيح"),email:z.email("البريد غير صحيح"),taxNumber:z.string().min(3,"الرقم الضريبي مطلوب")});
export type PartyInput=z.infer<typeof partySchema>;
export function PartyForm({open,onClose,onSave,initial,title}:{open:boolean;onClose:()=>void;onSave:(v:PartyInput)=>void;initial?:Party;title:string}){const {register,handleSubmit,formState:{errors}}=useForm<PartyInput>({resolver:zodResolver(partySchema),values:initial?{name:initial.name,code:initial.code,phone:initial.phone,email:initial.email,taxNumber:initial.taxNumber}:undefined,defaultValues:{name:"",code:"",phone:"",email:"",taxNumber:""}});return <Modal title={title} open={open} onClose={onClose}><form onSubmit={handleSubmit(onSave)}><div className="dialog-body form-grid"><Field label="الاسم" error={errors.name?.message}><input className="input" {...register("name")}/></Field><Field label="الكود" error={errors.code?.message}><input className="input" dir="ltr" {...register("code")}/></Field><Field label="الهاتف" error={errors.phone?.message}><input className="input" dir="ltr" {...register("phone")}/></Field><Field label="البريد" error={errors.email?.message}><input className="input" dir="ltr" {...register("email")}/></Field><Field label="الرقم الضريبي" error={errors.taxNumber?.message}><input className="input" dir="ltr" {...register("taxNumber")}/></Field></div><FormFoot onClose={onClose}/></form></Modal>}

const projectSchema=z.object({code:z.string().min(2,"الكود مطلوب"),name:z.string().min(3,"اسم المشروع مطلوب"),customerId:z.string().min(1,"اختر العميل"),companyId:z.string().min(1),location:z.string().min(2,"الموقع مطلوب"),contractValue:z.number().positive("يجب أن تكون القيمة أكبر من صفر"),budget:z.number().positive("يجب أن تكون الميزانية أكبر من صفر"),progress:z.number().min(0).max(100),startDate:z.string().min(1),endDate:z.string().min(1)}).refine(v=>new Date(v.endDate)>new Date(v.startDate),{message:"تاريخ النهاية يجب أن يلي البداية",path:["endDate"]});
export type ProjectInput=z.infer<typeof projectSchema>;
export function ProjectForm({open,onClose,onSave,initial,companies,customers}:{open:boolean;onClose:()=>void;onSave:(v:ProjectInput)=>void;initial?:Project;companies:Company[];customers:Party[]}){const defaults=initial?{code:initial.code,name:initial.name,customerId:initial.customerId,companyId:initial.companyId,location:initial.location,contractValue:initial.contractValue,budget:initial.budget,progress:initial.progress,startDate:initial.startDate,endDate:initial.endDate}:{code:"",name:"",customerId:customers[0]?.id??"",companyId:companies[0]?.id??"",location:"",contractValue:0,budget:0,progress:0,startDate:"",endDate:""};const {register,handleSubmit,control,formState:{errors}}=useForm<ProjectInput>({resolver:zodResolver(projectSchema),values:defaults});return <Modal title={initial?"تعديل المشروع":"إنشاء مشروع"} open={open} onClose={onClose}><form onSubmit={handleSubmit(onSave)}><div className="dialog-body form-grid"><div className="section-title">بيانات المشروع</div><Field label="كود المشروع" error={errors.code?.message}><input className="input" dir="ltr" {...register("code")}/></Field><Field label="اسم المشروع" error={errors.name?.message}><input className="input" {...register("name")}/></Field><Field label="الشركة" error={errors.companyId?.message}><Controller name="companyId" control={control} render={({field})=><select className="input" {...field}>{companies.filter(c=>c.status==="active").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}/></Field><Field label="العميل" error={errors.customerId?.message}><Controller name="customerId" control={control} render={({field})=><select className="input" {...field}>{customers.filter(c=>c.status==="active").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}/></Field><Field label="الموقع" error={errors.location?.message}><input className="input" {...register("location")}/></Field><div/><div className="section-title">البيانات المالية والجدول الزمني</div><Field label="قيمة العقد" error={errors.contractValue?.message}><input className="input" type="number" {...register("contractValue",{valueAsNumber:true})}/></Field><Field label="الميزانية" error={errors.budget?.message}><input className="input" type="number" {...register("budget",{valueAsNumber:true})}/></Field><Field label="نسبة الإنجاز %" error={errors.progress?.message}><input className="input" type="number" {...register("progress",{valueAsNumber:true})}/></Field><div/><Field label="تاريخ البداية" error={errors.startDate?.message}><input className="input" type="date" {...register("startDate")}/></Field><Field label="تاريخ النهاية" error={errors.endDate?.message}><input className="input" type="date" {...register("endDate")}/></Field></div><FormFoot onClose={onClose}/></form></Modal>}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}{error&&<span className="error">{error}</span>}</div>}
function FormFoot({onClose,loading=false}:{onClose:()=>void;loading?:boolean}){return <div className="dialog-foot"><button type="button" className="btn btn-secondary" onClick={onClose}>إلغاء</button><button type="submit" className="btn btn-primary" disabled={loading}>{loading?"جارٍ الحفظ...":"حفظ البيانات"}</button></div>}
